// 🤲 Du'as curadas — "Du'a del día"
// 🔢 60 du'as: 23 originales + 37 añadidos (30 coránicos con traducción de Isa
//    García extraída de data/garcia/*.json y 7 de hadiz según la edición española
//    de "La Fortaleza del Musulmán").
// v36: Traducciones españolas REVISADAS y sustituidas por versiones de fuentes
//      acreditadas (ya no traducciones literales improvisadas):
//   • Du'as coránicas → Traducción comentada del Corán, Lic. M. Isa García
//     (misma fuente oficial que usa la app para las aleyas: data/garcia/*.json).
//   • Du'as de hadiz → traducción española estándar publicada de
//     "La Fortaleza del Musulmán" (Hisnul Muslim, ed. Darussalam).
//   • NUEVO: campo translation_ar con el texto árabe completo, para que la
//     interfaz en árabe muestre el du'a correcto (antes se mostraba español).
const DAILY_DUAS = [
  {
    id: 'morning_1',
    title: "Du'a de la mañana",
    title_ar: 'دعاء الصباح',
    title_en: 'Morning supplication',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
    transliteration: 'Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namutu, wa ilayka an-nushur',
    translation_es: 'Oh Dios, por Ti llegamos a la mañana, por Ti llegamos a la tarde, por Ti vivimos y por Ti morimos, y hacia Ti es la resurrección.',
    translation_ar: 'اللهم بك أصبحنا، وبك أمسينا، وبك نحيا، وبك نموت، وإليك النشور',
    translation_en: 'O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.',
    source: 'At-Tirmidhi 3391',
  },
  {
    id: 'guidance_1',
    title: 'Para pedir guía',
    title_ar: 'دعاء طلب الهداية',
    title_en: 'Asking for guidance',
    arabic: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ',
    transliteration: 'Ihdina as-sirat al-mustaqim',
    // Al-Fatihah 1:6 — Isa García
    translation_es: '¡Guíanos por el camino recto!',
    translation_ar: 'اهدنا الصراط المستقيم',
    translation_en: 'Guide us along the straight path.',
    source: 'Al-Fatihah 1:6',
  },
  {
    id: 'forgiveness_1',
    title: 'Para pedir perdón',
    title_ar: 'دعاء طلب المغفرة',
    title_en: 'Asking for forgiveness',
    arabic: 'رَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ',
    transliteration: 'Rabbana zalamna anfusana wa in lam taghfir lana wa tarhamna lanakunanna min al-khasirin',
    // Al-A'raf 7:23 — Isa García
    translation_es: '¡Señor nuestro! Hemos sido injustos con nosotros mismos; si no nos perdonas y nos tienes misericordia, seremos de los perdidos.',
    translation_ar: 'ربنا ظلمنا أنفسنا وإن لم تغفر لنا وترحمنا لنكونن من الخاسرين',
    translation_en: 'Our Lord, we have wronged ourselves; if You do not forgive us and have mercy upon us, we will surely be among the losers.',
    source: "Al-A'raf 7:23",
  },
  {
    id: 'knowledge_1',
    title: 'Para pedir conocimiento útil',
    title_ar: 'دعاء طلب العلم النافع',
    title_en: 'Asking for beneficial knowledge',
    arabic: 'رَبِّ زِدْنِي عِلْمًا',
    transliteration: "Rabbi zidni 'ilman",
    // Ta-Ha 20:114 — Isa García
    translation_es: '¡Oh, Señor mío! Increméntame en conocimiento.',
    translation_ar: 'رب زدني علما',
    translation_en: 'My Lord, increase me in knowledge.',
    source: 'Ta-Ha 20:114',
  },
  {
    id: 'parents_1',
    title: 'Por los padres',
    title_ar: 'الدعاء للوالدين',
    title_en: 'For the parents',
    arabic: 'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    transliteration: 'Rabbi-rhamhuma kama rabbayani saghira',
    // Al-Isra 17:24 — Isa García
    translation_es: '¡Oh, Señor mío! Ten misericordia de ellos como ellos la tuvieron conmigo cuando me criaron siendo niño.',
    translation_ar: 'رب ارحمهما كما ربياني صغيرا',
    translation_en: 'My Lord, have mercy upon them as they raised me when I was small.',
    source: 'Al-Isra 17:24',
  },
  {
    id: 'protection_1',
    title: 'Protección al salir de casa',
    title_ar: 'دعاء الخروج من المنزل',
    title_en: 'When leaving the house',
    arabic: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: "Bismillah, tawakkaltu 'ala Allah, wa la hawla wa la quwwata illa billah",
    // Hisnul Muslim — traducción española publicada (Darussalam)
    translation_es: 'En el nombre de Dios, en Dios confío, y no hay poder ni fuerza excepto en Dios.',
    translation_ar: 'بسم الله، توكلت على الله، ولا حول ولا قوة إلا بالله',
    translation_en: 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
    source: 'Abu Dawud 5095, At-Tirmidhi 3426',
  },
  {
    id: 'anxiety_1',
    title: 'Para alivio de la ansiedad',
    title_ar: 'دعاء تفريج الهم',
    title_en: 'For relief from anxiety',
    arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: "Hasbuna Allah wa ni'ma al-wakil",
    // Al-i'Imran 3:173 — Isa García
    translation_es: 'Dios es suficiente para nosotros, porque Él es el mejor protector.',
    translation_ar: 'حسبنا الله ونعم الوكيل',
    translation_en: 'Allah is sufficient for us, and He is the best Disposer of affairs.',
    source: "Al-i'Imran 3:173",
  },

  // ================================================================
  // v36: Expansión de la base de du'as del día — du'as auténticos y
  // conocidos, con sabiduría y lección. Traducciones españolas de fuentes
  // acreditadas: las coránicas según Isa García (data/garcia) y las de
  // hadiz según la traducción publicada de La Fortaleza del Musulmán.
  // ================================================================
  {
    id: 'sayyid_istighfar_day',
    title: 'Sayyid al-Istighfar (la mejor súplica de perdón)',
    title_ar: 'سيد الاستغفار',
    title_en: 'Sayyid al-Istighfar (the chief supplication for forgiveness)',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: "Allahumma anta Rabbi, la ilaha illa Ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayya, wa abu'u bidhanbi, faghfir li fa innahu la yaghfirudh-dhunuba illa Ant",
    translation_es: 'Oh Dios, Tú eres mi Señor, no hay otra divinidad sino Tú. Tú me creaste y yo soy Tu siervo, y me comprometo a cumplir Tu pacto y Tu promesa en la medida de mis posibilidades. Me refugio en Ti del mal que he cometido. Reconozco Tus bendiciones sobre mí y reconozco mis pecados; perdóname, pues nadie perdona los pecados excepto Tú.',
    translation_ar: 'اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت، أعوذ بك من شر ما صنعت، أبوء لك بنعمتك علي، وأبوء بذنبي، فاغفر لي فإنه لا يغفر الذنوب إلا أنت',
    translation_en: 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant; I abide by Your covenant and Your promise as best I can. I seek refuge with You from the evil I have committed. I acknowledge Your favor upon me and I acknowledge my sins; forgive me, for none forgives sins but You.',
    source: 'Al-Bujari 6306',
  },
  {
    id: 'rabban_atina_day',
    title: 'La súplica más completa',
    title_ar: 'الدعاء الجامع — ربنا آتنا في الدنيا حسنة',
    title_en: 'The most comprehensive supplication',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: "Rabbana atina fid-dunya hasanah, wa fil-akhirati hasanah, wa qina 'adhab an-nar",
    // Al-Baqarah 2:201 — Isa García
    translation_es: '¡Señor nuestro! Danos bienestar en esta vida y en la otra, y presérvanos del tormento del Fuego.',
    translation_ar: 'ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار',
    translation_en: 'Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.',
    source: 'Al-Baqarah 2:201',
  },
  {
    id: 'sayyid_shafa_day',
    title: "Du'a de la curación",
    title_ar: 'دعاء الشفاء',
    title_en: 'Supplication for healing',
    arabic: 'اللَّهُمَّ رَبَّ النَّاسِ، أَذْهِبِ الْبَأْسَ، اشْفِ أَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا',
    transliteration: "Allahumma Rabban-nas, adhhib al-ba's, ishfi Antash-Shafi, la shifa'a illa shifa'uk, shifa'an la yughadiru saqama",
    translation_es: 'Oh Dios, Señor de los hombres, aleja el mal y cura, pues Tú eres el Sanador. No hay curación sino la Tuya: una curación que no deja enfermedad alguna.',
    translation_ar: 'اللهم رب الناس، أذهب البأس، اشف أنت الشافي، لا شفاء إلا شفاؤك، شفاء لا يغادر سقما',
    translation_en: 'O Allah, Lord of mankind, remove the harm and heal, for You are the Healer. There is no healing except Your healing — a healing that leaves no illness behind.',
    source: 'Al-Bujari 5675, Muslim 2191',
  },
  {
    id: 'rizq_halal_day',
    title: 'Suficiencia en lo lícito',
    title_ar: 'دعاء الكفاف بالحلال',
    title_en: 'Sufficiency through the lawful',
    arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    transliteration: "Allahumma-kfini bihalalika 'an haramik, wa aghnini bifadlika 'amman siwak",
    translation_es: 'Oh Dios, bástame con lo lícito que me has permitido en lugar de lo ilícito que me has prohibido, y enriquéceme con Tu favor de modo que no necesite a nadie más que a Ti.',
    translation_ar: 'اللهم اكفني بحلالك عن حرامك، وأغنني بفضلك عمن سواك',
    translation_en: 'O Allah, suffice me with Your lawful against Your unlawful, and enrich me by Your bounty from all besides You.',
    source: 'At-Tirmidhi 3563',
  },
  {
    id: 'hamm_hazan_day',
    title: 'Contra la preocupación y la tristeza',
    title_ar: 'دعاء الهم والحزن',
    title_en: 'Against worry and sorrow',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan, wal-'ajzi wal-kasal, wal-bukhli wal-jubn, wa dala'id-dayni wa ghalabatir-rijal",
    translation_es: 'Oh Dios, me refugio en Ti de la preocupación y la tristeza, de la incapacidad y la pereza, de la avaricia y la cobardía, y del peso de las deudas y la opresión de los hombres.',
    translation_ar: 'اللهم إني أعوذ بك من الهم والحزن، والعجز والكسل، والبخل والجبن، وضلع الدين وغلبة الرجال',
    translation_en: 'O Allah, I seek refuge in You from worry and sorrow, from incapacity and laziness, from miserliness and cowardice, and from the burden of debts and the overpowering of men.',
    source: 'Al-Bujari 6369',
  },
  {
    id: 'knowledge_beneficial_day',
    title: 'Conocimiento beneficioso y buen sustento',
    title_ar: 'دعاء العلم النافع والرزق الطيب',
    title_en: 'Beneficial knowledge and good provision',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
    transliteration: "Allahumma inni as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbala",
    translation_es: 'Oh Dios, Te pido un conocimiento beneficioso, un sustento bueno y lícito, y obras que Te sean aceptadas.',
    translation_ar: 'اللهم إني أسألك علما نافعا، ورزقا طيبا، وعملا متقبلا',
    translation_en: 'O Allah, I ask You for beneficial knowledge, good and lawful provision, and deeds that are accepted.',
    source: 'Ibn Majah 925',
  },
  {
    id: 'allahumma_ainni_day',
    title: 'Ayuda para recordar y agradecer',
    title_ar: 'دعاء طلب الإعانة على الذكر والشكر',
    title_en: 'Help in remembrance and gratitude',
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ، وَشُكْرِكَ، وَحُسْنِ عِبَادَتِكَ',
    transliteration: "Allahumma a'inni 'ala dhikrika, wa shukrika, wa husni 'ibadatik",
    translation_es: 'Oh Dios, ayúdame a recordarte, a agradecerte y a adorarte de la mejor manera.',
    translation_ar: 'اللهم أعني على ذكرك، وشكرك، وحسن عبادتك',
    translation_en: 'O Allah, help me to remember You, to thank You, and to worship You in the best manner.',
    source: 'Abu Dawud 1522',
  },
  {
    id: 'istighfar_tawba_day',
    title: 'Perdón y regreso a Dios',
    title_ar: 'دعاء الاستغفار والتوبة',
    title_en: 'Forgiveness and repentance',
    arabic: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيَّ الْقَيُّومَ وَأَتُوبُ إِلَيْهِ',
    transliteration: "Astaghfirullah al-'Adhim alladhi la ilaha illa Huwa al-Hayyul-Qayyum, wa atubu ilayh",
    translation_es: 'Pido perdón a Dios el Magnífico, no hay otra divinidad sino Él, el Viviente, el Sustentador, y a Él me retorno arrepentido.',
    translation_ar: 'أستغفر الله العظيم الذي لا إله إلا هو الحي القيوم وأتوب إليه',
    translation_en: 'I seek the forgiveness of Allah the Magnificent, besides Whom there is no god, the Living, the Sustainer, and I repent to Him.',
    source: 'Abu Dawud 1517, At-Tirmidhi 3577',
  },
  {
    id: 'ya_hayyu_day',
    title: 'Ya Hayyu ya Qayyum',
    title_ar: 'يا حي يا قيوم',
    title_en: 'O Ever-Living, O Sustainer',
    arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ',
    transliteration: "Ya Hayyu ya Qayyum, birahmatika astaghith, aslih li sha'ni kullahu, wa la takilni ila nafsi tarfata 'ayn",
    translation_es: '¡Oh Viviente, oh Sustentador! Imploro auxilio por Tu misericordia. Dispón todos mis asuntos y no me dejes a cargo de mí mismo ni un abrir y cerrar de ojos.',
    translation_ar: 'يا حي يا قيوم برحمتك أستغيث، أصلح لي شأني كله، ولا تكلني إلى نفسي طرفة عين',
    translation_en: 'O Ever-Living, O Sustainer, by Your mercy I seek assistance. Set right all of my affairs, and do not leave me to myself even for the blink of an eye.',
    source: 'At-Tirmidhi 3524',
  },
  {
    id: 'dunia_day',
    title: 'Que la vida mundanal no sea nuestra mayor preocupación',
    title_ar: 'دعاء ألا تكون الدنيا أكبر همنا',
    title_en: 'That this world not be our greatest concern',
    arabic: 'اللَّهُمَّ لَا تَجْعَلِ الدُّنْيَا أَكْبَرَ هَمِّنَا، وَلَا مَبْلَغَ عِلْمِنَا، وَلَا إِلَى النَّارِ مَصِيرَنَا، وَاجْعَلِ الْجَنَّةَ هِيَ دَارَنَا',
    transliteration: "Allahumma la taj'alid-dunya akbara hammina, wa la mablagha 'ilmina, wa la ilan-nari masirana, waj'alil-jannata hiya darana",
    translation_es: 'Oh Dios, no hagas que la vida mundanal sea nuestra mayor preocupación ni el límite de nuestro conocimiento, ni que el Fuego sea nuestro destino, y haz que el Paraíso sea nuestra morada.',
    translation_ar: 'اللهم لا تجعل الدنيا أكبر همنا، ولا مبلغ علمنا، ولا إلى النار مصيرنا، واجعل الجنة هي دارنا',
    translation_en: 'O Allah, do not make this world our greatest concern nor the limit of our knowledge, nor the Fire our destination, and make Paradise our abode.',
    source: 'At-Tabarani, Al-Mu\'yam al-Awsat 4774',
  },
  {
    id: 'salat_nabi_day',
    title: 'Bendiciones sobre el Profeta ﷺ',
    title_ar: 'الصلاة على النبي ﷺ',
    title_en: 'Blessings upon the Prophet ﷺ',
    arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ',
    transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad",
    translation_es: 'Oh Dios, bendice a Mujámmad y a la familia de Mujámmad.',
    translation_ar: 'اللهم صل على محمد وعلى آل محمد',
    translation_en: 'O Allah, send Your blessings upon Muhammad and upon the family of Muhammad.',
    source: 'Al-Bujari 3370, Muslim 406',
  },
  // ---- Du'as coránicas de los profetas (Isa García) ----
  {
    id: 'dua_nuh_day',
    title: "Du'a de Nuh عليه السلام",
    title_ar: 'دعاء نوح عليه السلام',
    title_en: "Supplication of Noah, peace be upon him",
    arabic: 'أَنِّي مَغْلُوبٌ فَانتَصِرْ',
    transliteration: 'Anni maghlubun fantasir',
    // Al-Qamar 54:10 — Isa García
    translation_es: '¡Me han vencido, Te pido ayuda!',
    translation_ar: 'أني مغلوب فانتصر',
    translation_en: 'I have been overcome, so help me!',
    source: 'Al-Qamar 54:10',
  },
  {
    id: 'dua_ayyub_day',
    title: "Du'a de Ayyub عليه السلام (paciencia en la enfermedad)",
    title_ar: 'دعاء أيوب عليه السلام',
    title_en: "Supplication of Job, peace be upon him",
    arabic: 'أَنِّي مَسَّنِيَ الضُّرُّ وَأَنْتَ أَرْحَمُ الرَّاحِمِينَ',
    transliteration: "Anni massaniyad-durru wa Anta arhamur-rahimin",
    // Al-Anbiya 21:83 — Isa García
    translation_es: 'He sido probado con enfermedades, pero Tú eres el más Misericordioso.',
    translation_ar: 'أني مسني الضر وأنت أرحم الراحمين',
    translation_en: 'Indeed, adversity has touched me, and You are the Most Merciful of the merciful.',
    source: 'Al-Anbiya 21:83',
  },
  {
    id: 'dua_musa_need_day',
    title: "Du'a de Musa عليه السلام ante la necesidad",
    title_ar: 'دعاء موسى عليه السلام عند الحاجة',
    title_en: "Supplication of Moses in need",
    arabic: 'رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ',
    transliteration: "Rabbi inni lima anzalta ilayya min khayrin faqir",
    // Al-Qasas 28:24 — Isa García
    translation_es: '¡Señor mío! Realmente necesito cualquier gracia que me concedas.',
    translation_ar: 'رب إني لما أنزلت إلي من خير فقير',
    translation_en: 'My Lord, indeed I am, for whatever good You would send down to me, in need.',
    source: 'Al-Qasas 28:24',
  },
  {
    id: 'dua_yunus_day',
    title: "Du'a de Yunus عليه السلام (alivio de toda angustia)",
    title_ar: 'دعاء يونس عليه السلام',
    title_en: "Supplication of Jonah, peace be upon him",
    arabic: 'لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',
    transliteration: 'La ilaha illa Anta, subhanaka, inni kuntu minaz-zalimin',
    // Al-Anbiya 21:87 — Isa García
    translation_es: 'No hay otra divinidad más que Tú. ¡Glorificado seas! En verdad he sido de los injustos.',
    translation_ar: 'لا إله إلا أنت سبحانك إني كنت من الظالمين',
    translation_en: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
    source: 'Al-Anbiya 21:87',
  },
  {
    id: 'dua_ibrahim_child_day',
    title: "Du'a de Ibrahim عليه السلام por la descendencia",
    title_ar: 'دعاء إبراهيم عليه السلام للذرية',
    title_en: "Supplication of Abraham for offspring",
    arabic: 'رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ',
    transliteration: 'Rabbi hab li minas-salihin',
    // As-Saffat 37:100 — Isa García
    translation_es: '¡Oh, Señor mío! Concédeme un hijo justo.',
    translation_ar: 'رب هب لي من الصالحين',
    translation_en: 'My Lord, grant me a righteous son.',
    source: 'As-Saffat 37:100',
  },

  {
    id: 'dua_ibrahim_build',
    title: "Para que Allah acepte la obra",
    title_ar: "دعاء تقبل العمل",
    title_en: "For acceptance of one's work",
    arabic: "رَبَّنَا تَقَبَّلْ مِنَّآ ۖ إِنَّكَ أَنتَ ٱلسَّمِيعُ ٱلْعَلِيمُ",
    transliteration: "Rabbana taqabbal minna, innaka anta as-sami'u al-'alim",
    // Al-Baqarah 2:127 — Isa García
    translation_es: "Y [recuerden] cuando Abraham e Ismael levantaron los cimientos de La Casa, dijeron: “¡Oh, Señor! Acepta nuestra obra. Tú eres el que todo lo oye, todo lo sabe”.",
    translation_ar: "ربنا تقبل منا إنك أنت السميع العليم",
    translation_en: "Our Lord, accept this from us; indeed, You are the Hearing, the Knowing.",
    source: "Al-Baqarah 2:127",
  },
  {
    id: 'dua_ibrahim_islam',
    title: "Para vivir y morir en sumisión",
    title_ar: "دعاء الثبات على الإسلام",
    title_en: "To live submitted to Allah",
    arabic: "رَبَّنَا وَٱجْعَلْنَا مُسْلِمَيْنِ لَكَ وَمِن ذُرِّيَّتِنَآ أُمَّةً مُّسْلِمَةً لَّكَ وَأَرِنَا مَنَاسِكَنَا وَتُبْ عَلَيْنَآ ۖ إِنَّكَ أَنتَ ٱلتَّوَّابُ ٱلرَّحِيمُ",
    transliteration: "Rabbana waj'alna muslimayni laka, wa min dhurriyyatina ummatan muslimatan lak, wa arina manasikana, wa tub 'alayna, innaka anta at-tawwabu ar-rahim",
    // Al-Baqarah 2:128 — Isa García
    translation_es: "“¡Señor nuestro! Haz que nosotros nos entreguemos a Tu voluntad, y que nuestra descendencia también lo haga [como una nación de musulmanes]. Enséñanos nuestros ritos para la pe-",
    translation_ar: "ربنا اجعلنا مسلمين لك ومن ذريتنا أمة مسلمة لك",
    translation_en: "Our Lord, make us submissive to You and from our descendants a community submissive to You.",
    source: "Al-Baqarah 2:128",
  },
  {
    id: 'dua_talut_army',
    title: "Para la firmeza ante la prueba",
    title_ar: "دعاء الصبر والثبات",
    title_en: "For steadfastness in trial",
    arabic: "رَبَّنَآ أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَٱنصُرْنَا عَلَى ٱلْقَوْمِ ٱلْكَٰفِرِينَ",
    transliteration: "Rabbana afrigh 'alayna sabran, wa thabbit aqdamana, wansurna 'ala al-qawmi al-kafirin",
    // Al-Baqarah 2:250 — Isa García
    translation_es: "Al enfrentarse a Goliat y sus soldados suplicaban: “¡Oh, Señor nuestro! Danos paciencia, mantennos firmes y concédenos la victoria sobre los que niegan la verdad”.",
    translation_ar: "ربنا أفرغ علينا صبراً وثبت أقدامنا",
    translation_en: "Our Lord, pour patience upon us, make our feet firm, and give us victory.",
    source: "Al-Baqarah 2:250",
  },
  {
    id: 'dua_qulub',
    title: "Para que el corazón no se desvíe",
    title_ar: "دعاء الثبات على الهداية",
    title_en: "For a heart firm in guidance",
    arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ ٱلْوَهَّابُ",
    transliteration: "Rabbana la tuzigh qulubana ba'da idh hadaytana, wa hab lana min ladunka rahmah, innaka anta al-wahhab",
    // Aal-i-Imraan 3:8 — Isa García
    translation_es: "¡Señor nuestro! No permitas que nuestros corazones se desvíen después de habernos guiado. Concédenos Tu misericordia, Tú eres el Dadivoso.",
    translation_ar: "ربنا لا تزغ قلوبنا بعد إذ هديتنا",
    translation_en: "Our Lord, do not let our hearts deviate after You have guided us.",
    source: "Aal-i-Imraan 3:8",
  },
  {
    id: 'dua_amanna_nar',
    title: "Perdón y protección del Fuego",
    title_ar: "دعاء المغفرة والنجاة من النار",
    title_en: "Forgiveness and salvation",
    arabic: "رَبَّنَآ إِنَّنَآ ءَامَنَّا فَٱغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ ٱلنَّارِ",
    transliteration: "Rabbana innana amanna, faghfir lana dhunubana, wa qina 'adhaba an-nar",
    // Aal-i-Imraan 3:16 — Isa García
    translation_es: "quienes dicen: “¡Señor nuestro! Creemos en Ti. Perdónanos nuestros pecados y líbranos del castigo del Fuego”.",
    translation_ar: "ربنا إننا آمنا فاغفر لنا ذنوبنا وقنا عذاب النار",
    translation_en: "Our Lord, we have believed, so forgive us our sins and protect us from the punishment of the Fire.",
    source: "Aal-i-Imraan 3:16",
  },
  {
    id: 'dua_mulk',
    title: "Reconocer el dominio de Allah",
    title_ar: "دعاء الملك لله",
    title_en: "Allah, Owner of sovereignty",
    arabic: "ٱللَّهُمَّ مَٰلِكَ ٱلْمُلْكِ تُؤْتِى ٱلْمُلْكَ مَن تَشَآءُ وَتَنزِعُ ٱلْمُلْكَ مِمَّن تَشَآءُ وَتُعِزُّ مَن تَشَآءُ وَتُذِلُّ مَن تَشَآءُ ۖ بِيَدِكَ ٱلْخَيْرُ ۖ إِنَّكَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ",
    transliteration: "Allahumma malika al-mulki tu'ti al-mulka man tasha', wa tanzi'u al-mulka mimman tasha', wa tu'izzu man tasha', wa tudhillu man tasha', biyadika al-khayr, innaka 'ala kulli shay'in qadir",
    // Aal-i-Imraan 3:26 — Isa García
    translation_es: "¡Oh, Dios, Soberano Absoluto! Tú concedes el poder a quien quieres y se lo quitas a quien quieres, fortaleces a quien quieres y humillas a quien quieres. Todo el bien descansa en Tus manos. Tú tienes poder sobre todas las cosas.",
    translation_ar: "اللهم مالك الملك تؤتي الملك من تشاء",
    translation_en: "O Allah, Owner of sovereignty, You give and take power; in Your hand is all good.",
    source: "Aal-i-Imraan 3:26",
  },
  {
    id: 'dua_zakariyya',
    title: "Para pedir descendencia buena",
    title_ar: "دعاء زكريا بطلب الذرية",
    title_en: "Zakariyya's prayer for offspring",
    arabic: "رَبِّ هَبْ لِى مِن لَّدُنكَ ذُرِّيَّةً طَيِّبَةً ۖ إِنَّكَ سَمِيعُ ٱلدُّعَآءِ",
    transliteration: "Rabbi hab li min ladunka dhurriyyatan tayyibah, innaka sami'u ad-du'a'",
    // Aal-i-Imraan 3:38 — Isa García
    translation_es: "En el templo, Zacarías invocó a su Señor diciendo: “¡Señor mío! Concédeme una descendencia piadosa, Tú escuchas los ruegos”.",
    translation_ar: "رب هب لي من لدنك ذرية طيبة إنك سميع الدعاء",
    translation_en: "My Lord, grant me from Yourself good offspring; indeed, You are the Hearer of supplication.",
    source: "Aal-i-Imraan 3:38",
  },
  {
    id: 'dua_hawariyyun',
    title: "Para seguir a los mensajeros",
    title_ar: "دعاء الحواريين",
    title_en: "Prayer of the disciples",
    arabic: "رَبَّنَآ ءَامَنَّا بِمَآ أَنزَلْتَ وَٱتَّبَعْنَا ٱلرَّسُولَ فَٱكْتُبْنَا مَعَ ٱلشَّٰهِدِينَ",
    transliteration: "Rabbana amanna bima anzalta wattaba'na ar-rasula, faktubna ma'a ash-shahidin",
    // Aal-i-Imraan 3:53 — Isa García
    translation_es: "¡Señor nuestro! Creemos en lo que has revelado y seguimos a Tu Profeta. Cuéntanos entre los que dan testimonio de fe”.",
    translation_ar: "ربنا آمنا بما أنزلت واتبعنا الرسول فاكتبنا مع الشاهدين",
    translation_en: "Our Lord, we have believed in what You revealed and followed the Messenger, so write us among the witnesses.",
    source: "Aal-i-Imraan 3:53",
  },
  {
    id: 'dua_israf',
    title: "Perdón por los excesos",
    title_ar: "دعاء المغفرة من الإسراف",
    title_en: "Forgiveness for excesses",
    arabic: "رَبَّنَا ٱغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَٰفَنَا فِىٓ أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا وَٱنصُرْنَا عَلَى ٱلْقَوْمِ ٱلْكَٰفِرِينَ",
    transliteration: "Rabbana ighfir lana dhunubana wa israfana fi amrina, wa thabbit aqdamana, wansurna 'ala al-qawmi al-kafirin",
    // Aal-i-Imraan 3:147 — Isa García
    translation_es: "No pronunciaban otras palabras más que: “¡Oh, Señor nuestro! Perdona nuestros pecados y nuestros excesos. Afirma nuestros pasos y concédenos el triunfo sobre los que rechazan la verdad”.",
    translation_ar: "ربنا اغفر لنا ذنوبنا وإسرافنا في أمرنا",
    translation_en: "Our Lord, forgive us our sins and our excesses, make our feet firm and grant us victory.",
    source: "Aal-i-Imraan 3:147",
  },
  {
    id: 'dua_samina',
    title: "Respuesta a la llamada de la fe",
    title_ar: "دعاء الاستجابة للإيمان",
    title_en: "Answering the call to faith",
    arabic: "رَبَّنَآ إِنَّنَا سَمِعْنَا مُنَادِيًا يُنَادِى لِلْإِيمَٰنِ أَنْ ءَامِنُوا۟ بِرَبِّكُمْ فَـَٔامَنَّا ۚ رَبَّنَا فَٱغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّـَٔاتِنَا وَتَوَفَّنَا مَعَ ٱلْأَبْرَارِ",
    transliteration: "Rabbana innana sami'na munadiyan yunadi lil-imani an aminu birabbikum fa-amanna, rabbana faghfir lana dhunubana, wa kaffir 'anna sayyi'atina, wa tawaffana ma'a al-abrar",
    // Aal-i-Imraan 3:193 — Isa García
    translation_es: "¡Señor nuestro! Hemos oído a quien convocaba a la fe, diciendo: ‘Crean en su Señor’, y creímos. ¡Señor nuestro! Perdona nuestros pecados, borra nuestras malas acciones y, al morir, reúnenos con los piadosos.",
    translation_ar: "ربنا إننا سمعنا منادياً ينادي للإيمان فآمنا",
    translation_en: "Our Lord, we heard a caller calling to faith and we believed; forgive us and let us die with the righteous.",
    source: "Aal-i-Imraan 3:193",
  },
  {
    id: 'dua_waad',
    title: "Confiar en la promesa de Allah",
    title_ar: "دعاء وعد الله",
    title_en: "Trusting Allah's promise",
    arabic: "رَبَّنَا وَءَاتِنَا مَا وَعَدتَّنَا عَلَىٰ رُسُلِكَ وَلَا تُخْزِنَا يَوْمَ ٱلْقِيَٰمَةِ ۗ إِنَّكَ لَا تُخْلِفُ ٱلْمِيعَادَ",
    transliteration: "Rabbana wa atina ma wa'adtana 'ala rusulika, wa la tukhzina yawma al-qiyamah, innaka la tukhlifu al-mi'ad",
    // Aal-i-Imraan 3:194 — Isa García
    translation_es: "¡Señor nuestro! Concédenos lo que has prometido a través de Tus Mensajeros y no nos humilles el Día de la Resurrección. Tú no faltas a Tu promesa”.",
    translation_ar: "ربنا وآتنا ما وعدتنا على رسلك ولا تخزنا يوم القيامة",
    translation_en: "Our Lord, grant us what You promised through Your messengers and do not disgrace us on the Day of Resurrection.",
    source: "Aal-i-Imraan 3:194",
  },
  {
    id: 'dua_sabr_muslimin',
    title: "Morir como musulmanes",
    title_ar: "دعاء حسن الخاتمة",
    title_en: "For a good ending",
    arabic: "رَبَّنَآ أَفْرِغْ عَلَيْنَا صَبْرًا وَتَوَفَّنَا مُسْلِمِينَ",
    transliteration: "Rabbana afrigh 'alayna sabran, wa tawaffana muslimin",
    // Al-A'raf 7:126 — Isa García
    translation_es: "Solo te vengas de nosotros porque hemos creído cuando llega-",
    translation_ar: "ربنا أفرغ علينا صبراً وتوفنا مسلمين",
    translation_en: "Our Lord, pour patience upon us and let us die as Muslims.",
    source: "Al-A'raf 7:126",
  },
  {
    id: 'dua_musa_tawakkul',
    title: "Protección contra el pueblo opresor",
    title_ar: "دعاء النجاة من الظالمين",
    title_en: "Deliverance from oppressors",
    arabic: "عَلَى ٱللَّهِ تَوَكَّلْنَا ۚ رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلْقَوْمِ ٱلظَّٰلِمِينَ وَنَجِّنَا بِرَحْمَتِكَ مِنَ ٱلْقَوْمِ ٱلْكَٰفِرِينَ",
    transliteration: "'Ala Allahi tawakkalna, rabbana la taj'alna fitnatan lil-qawmi az-zalimin, wa najjina birahmatika mina al-qawmi al-kafirin",
    // Yunus 10:85-86 — Isa García
    translation_es: "Dijeron: “A Ti nos encomendamos, ¡oh, Señor nuestro! No permitas que nos domine este pueblo opresor. Y por Tu misericordia, sálvanos de la gente que se niega a creer”.",
    translation_ar: "على الله توكلنا ربنا لا تجعلنا فتنة للقوم الظالمين",
    translation_en: "In Allah we trust; our Lord, do not make us a trial for the oppressing people, and save us by Your mercy.",
    source: "Yunus 10:85-86",
  },
  {
    id: 'dua_yusuf_khatima',
    title: "Morir en el islam y unirse a los justos",
    title_ar: "دعاء يوسف بحسن الخاتمة",
    title_en: "Yusuf's prayer for a good end",
    arabic: "رَبِّ قَدْ ءَاتَيْتَنِى مِنَ ٱلْمُلْكِ وَعَلَّمْتَنِى مِن تَأْوِيلِ ٱلْأَحَادِيثِ ۚ فَاطِرَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ أَنتَ وَلِىِّۦ فِى ٱلدُّنْيَا وَٱلْءَاخِرَةِ ۖ تَوَفَّنِى مُسْلِمًا وَأَلْحِقْنِى بِٱلصَّٰلِحِينَ",
    transliteration: "Rabbi qad ataytani mina al-mulki wa 'allamtani min ta'wili al-ahadith, fatira as-samawati wal-ard, anta waliyyi fid-dunya wal-akhirah, tawaffani musliman wa alhiqni bis-salihin",
    // Yusuf 12:101 — Isa García
    translation_es: "¡Señor mío! Me has concedido autoridad y me has enseñado la interpretación de los sueños. ¡Creador de los cielos y la Tierra! Tú eres mi Protector en esta vida y en la otra, hazme morir sometido a Ti, y reúneme con los virtuosos”.",
    translation_ar: "رب توفني مسلماً وألحقني بالصالحين",
    translation_en: "My Lord, You are my Protector in this world and the Hereafter; let me die as a Muslim and join me with the righteous.",
    source: "Yusuf 12:101",
  },
  {
    id: 'dua_ibrahim_salah',
    title: "Para establecer la oración",
    title_ar: "دعاء إقامة الصلاة",
    title_en: "To establish prayer",
    arabic: "رَبِّ ٱجْعَلْنِى مُقِيمَ ٱلصَّلَوٰةِ وَمِن ذُرِّيَّتِى ۚ رَبَّنَا وَتَقَبَّلْ دُعَآءِ",
    transliteration: "Rabbi ij'alni muqima as-salati wa min dhurriyyati, rabbana wa taqabbal du'a'",
    // Ibrahim 14:40 — Isa García
    translation_es: "¡Oh, Señor mío! Haz que tanto mis descendientes como yo seamos fervientes practicantes de la oración. ¡Oh, Señor nuestro! Concédeme esta súplica.",
    translation_ar: "رب اجعلني مقيم الصلاة ومن ذريتي",
    translation_en: "My Lord, make me an establisher of prayer, and from my descendants as well; our Lord, accept my supplication.",
    source: "Ibrahim 14:40",
  },
  {
    id: 'dua_dukhul_sidq',
    title: "Entrada y salida con verdad",
    title_ar: "دعاء مدخل الصدق",
    title_en: "A truthful entrance and exit",
    arabic: "رَّبِّ أَدْخِلْنِى مُدْخَلَ صِدْقٍ وَأَخْرِجْنِى مُخْرَجَ صِدْقٍ وَٱجْعَل لِّى مِن لَّدُنكَ سُلْطَٰنًا نَّصِيرًا",
    transliteration: "Rabbi adkhilni mudkhala sidqin, wa akhrijni mukhraja sidqin, waj'al li min ladunka sultanan nasira",
    // Al-Isra 17:80 — Isa García
    translation_es: "Di: “¡Señor mío! Concédeme una entrada y una salida dignas [en todos los asuntos de mi vida], y concédeme los medios para lograr el triunfo”.",
    translation_ar: "رب أدخلني مدخل صدق وأخرجني مخرج صدق",
    translation_en: "My Lord, cause me to enter a sound entrance and to exit a sound exit, and grant me from Yourself a supporting authority.",
    source: "Al-Isra 17:80",
  },
  {
    id: 'dua_ashab_kahf',
    title: "Misericordia y acierto (jóvenes de la caverna)",
    title_ar: "دعاء أصحاب الكهف",
    title_en: "Prayer of the cave youth",
    arabic: "رَبَّنَآ ءَاتِنَا مِن لَّدُنكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا",
    transliteration: "Rabbana atina min ladunka rahmah, wa hayyi' lana min amrina rashada",
    // Al-Kahf 18:10 — Isa García
    translation_es: "Recuerda cuando los jóvenes se refugiaron en la caverna y dijeron: “¡Señor nuestro! Acógenos en Tu misericordia y concédenos que nuestra situación se solucione correctamente”. Entonces hice que durmieran en la caverna por muchos años. Luego hice que despertaran para distinguir cuál de los dos grupos [creyentes e incrédulos] calculaba mejor el tiempo que habían permanecido allí. Te relato su verdadera historia: Eran jóvenes que creían en su Señor y les aumenté su guía, fortalecí sus corazones cuando se reunieron [antes de dejar sus hogares y su gente] y dijeron: “Nuestro Señor es el Señor de los cielos y de la Tierra. No invocaremos nada fuera de Él, si lo hiciéramos estaríamos cometiendo una desviación. Nuestro pueblo adora fuera de Él falsas deidades. ¿Por qué no presentan un fundamento válido para hacerlo? ¿Acaso hay alguien más injusto que quien inventa una mentira y la atribuye a Dios?” [Dijo uno de ellos:] “Si se apartan de ellos y reniegan de cuanto adoran en vez de Dios, refúgiense en la caverna, que su Señor los cubrirá con Su misericordia y les facilitará una salida a su situación”. Se podía observar cómo el Sol naciente se alejaba de la caverna por la derecha dejándolos al ocultarse por la izquierda, mientras ellos permanecían en un espacio de la misma. Este es uno de los milagros de Dios. Aquel a quien Dios guíe estará bien encaminado, pero a quien deja en el extravío no podrá encontrar protector que lo guíe. Habrías creído que estaban despiertos, pero estaban dormidos. Los volteaba hacia la derecha y hacia la izquierda, y su perro estaba con las patas delanteras extendidas en la entrada. Si los hubieras visto, habrías huido aterrorizado.",
    translation_ar: "ربنا آتنا من لدنك رحمة وهيئ لنا من أمرنا رشداً",
    translation_en: "Our Lord, grant us mercy from Yourself and facilitate for us our affair in the right way.",
    source: "Al-Kahf 18:10",
  },
  {
    id: 'dua_musa_sadr',
    title: "Para expandir el pecho y facilitar el asunto",
    title_ar: "دعاء موسى بشرح الصدر",
    title_en: "Musa's prayer for relief",
    arabic: "رَبِّ ٱشْرَحْ لِى صَدْرِى وَيَسِّرْ لِىٓ أَمْرِى وَٱحْلُلْ عُقْدَةً مِّن لِّسَانِى يَفْقَهُوا۟ قَوْلِى",
    transliteration: "Rabbi ishrah li sadri, wa yassir li amri, wahlul 'uqdatan min lisani, yafqahu qawli",
    // Ta-Ha 20:25-28 — Isa García
    translation_es: "Dijo [Moisés]: “¡Oh, Señor mío! Abre mi corazón [y dame valor], facilita mi misión, suelta el nudo que hay en mi lengua4 para que comprendan mis palabras,",
    translation_ar: "رب اشرح لي صدري ويسر لي أمري",
    translation_en: "My Lord, expand for me my chest, ease my task for me, and untie the knot from my tongue.",
    source: "Ta-Ha 20:25-28",
  },
  {
    id: 'dua_nuh_munzal',
    title: "Para un buen destino",
    title_ar: "دعاء المنزل المبارك",
    title_en: "For a blessed landing",
    arabic: "رَّبِّ أَنزِلْنِى مُنزَلًا مُّبَارَكًا وَأَنتَ خَيْرُ ٱلْمُنزِلِينَ",
    transliteration: "Rabbi anzilni munzalan mubarakan, wa anta khayru al-munzilin",
    // Al-Mu'minun 23:29 — Isa García
    translation_es: "Y di: “¡Señor mío! Hazme llegar a un destino bendito, pues Tú eres Quien mejor hace llegar a destino”.",
    translation_ar: "رب أنزلني منزلاً مباركاً وأنت خير المنزلين",
    translation_en: "My Lord, let me land at a blessed landing place, and You are the best of hosts.",
    source: "Al-Mu'minun 23:29",
  },
  {
    id: 'dua_hamazat',
    title: "Refugio contra los demonios",
    title_ar: "دعاء الاستعاذة من الشياطين",
    title_en: "Refuge from the devils",
    arabic: "رَّبِّ أَعُوذُ بِكَ مِنْ هَمَزَٰتِ ٱلشَّيَٰطِينِ وَأَعُوذُ بِكَ رَبِّ أَن يَحْضُرُونِ",
    transliteration: "Rabbi a'udhu bika min hamazati ash-shayatin, wa a'udhu bika rabbi an yahdurun",
    // Al-Mu'minun 23:97-98 — Isa García
    translation_es: "Di: “¡Oh, Señor mío! Me refugio en Ti de los susurros de los demonios, y me refugio en Ti, oh, Señor, de su presencia maligna”.",
    translation_ar: "رب أعوذ بك من همزات الشياطين",
    translation_en: "My Lord, I seek refuge in You from the incitements of the devils, and I seek refuge in You lest they be present with me.",
    source: "Al-Mu'minun 23:97-98",
  },
  {
    id: 'dua_qurrata_ayun',
    title: "Para la familia y la descendencia",
    title_ar: "دعاء قرة الأعين",
    title_en: "Comfort of the eyes",
    arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَٰجِنَا وَذُرِّيَّٰتِنَا قُرَّةَ أَعْيُنٍ وَٱجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yuni, waj'alna lil-muttaqina imama",
    // Al-Furqan 25:74 — Isa García
    translation_es: "Aquellos que piden: “¡Oh, Señor nuestro! Agrácianos con cónyuges y descendientes que sean un motivo de alegría y tranquilidad para nosotros, y haz que seamos un ejemplo para los que tienen temor [de Dios]”.",
    translation_ar: "ربنا هب لنا من أزواجنا وذرياتنا قرة أعين",
    translation_en: "Our Lord, grant us from among our spouses and offspring comfort to our eyes, and make us leaders of the righteous.",
    source: "Al-Furqan 25:74",
  },
  {
    id: 'dua_ibrahim_hukm',
    title: "Sabiduría y buena reputación",
    title_ar: "دعاء الحكم ولسان الصدق",
    title_en: "Wisdom and truthful speech",
    arabic: "رَبِّ هَبْ لِى حُكْمًا وَأَلْحِقْنِى بِٱلصَّٰلِحِينَ وَٱجْعَل لِّى لِسَانَ صِدْقٍ فِى ٱلْءَاخِرِينَ",
    transliteration: "Rabbi hab li hukman, wa alhiqni bis-salihin, waj'al li lisana sidqin fil-akhirin",
    // Ash-Shu'ara 26:83-84 — Isa García
    translation_es: "¡Oh, Señor mío! Concédeme sabiduría y estar entre los justos. Concédeme tener una buena reputación entre las generaciones futuras.",
    translation_ar: "رب هب لي حكماً وألحقني بالصالحين",
    translation_en: "My Lord, grant me wisdom and join me with the righteous, and grant me a reputation of truth among later generations.",
    source: "Ash-Shu'ara 26:83-84",
  },
  {
    id: 'dua_sulayman_shukr',
    title: "Para agradecer las bendiciones",
    title_ar: "دعاء سليمان بالشكر",
    title_en: "Sulayman's prayer of gratitude",
    arabic: "رَبِّ أَوْزِعْنِىٓ أَنْ أَشْكُرَ نِعْمَتَكَ ٱلَّتِىٓ أَنْعَمْتَ عَلَىَّ وَعَلَىٰ وَٰلِدَىَّ وَأَنْ أَعْمَلَ صَٰلِحًا تَرْضَىٰهُ وَأَدْخِلْنِى بِرَحْمَتِكَ فِى عِبَادِكَ ٱلصَّٰلِحِينَ",
    transliteration: "Rabbi awzi'ni an ashkura ni'mataka allati an'amta 'alayya wa 'ala walidayya, wa an a'mala salihan tardahu, wa adkhilni birahmatika fi 'ibadika as-salihin",
    // An-Naml 27:19 — Isa García
    translation_es: "[Salomón] al oír lo que ella decía, sonrió y exclamó: “¡Señor mío! Haz que te agradezca los favores que nos has concedido, tanto a mí como a mis padres, que haga obras de bien que Te complazcan, y cuéntame, por Tu misericordia, entre Tus siervos justos”.",
    translation_ar: "رب أوزعني أن أشكر نعمتك",
    translation_en: "My Lord, enable me to be grateful for Your favor and to do righteous deeds that please You.",
    source: "An-Naml 27:19",
  },
  {
    id: 'dua_musa_tawba',
    title: "Arrepentimiento por un error grave",
    title_ar: "دعاء موسى بالتوبة",
    title_en: "Musa's repentance",
    arabic: "رَبِّ إِنِّى ظَلَمْتُ نَفْسِى فَٱغْفِرْ لِى",
    transliteration: "Rabbi inni zalamtu nafsi faghfir li",
    // Al-Qasas 28:16 — Isa García
    translation_es: "Dijo: “¡Señor mío! He sido injusto conmigo mismo; perdóname”. Y [Dios] lo perdonó, porque Él es Absolvedor, Misericordioso.",
    translation_ar: "رب إني ظلمت نفسي فاغفر لي",
    translation_en: "My Lord, indeed I have wronged myself, so forgive me.",
    source: "Al-Qasas 28:16",
  },
  {
    id: 'dua_kiram_arbain',
    title: "Al llegar a los cuarenta",
    title_ar: "دعاء بلوغ الأربعين",
    title_en: "Upon reaching maturity",
    arabic: "رَبِّ أَوْزِعْنِىٓ أَنْ أَشْكُرَ نِعْمَتَكَ ٱلَّتِىٓ أَنْعَمْتَ عَلَىَّ وَعَلَىٰ وَٰلِدَىَّ وَأَنْ أَعْمَلَ صَٰلِحًا تَرْضَىٰهُ وَأَصْلِحْ لِى فِى ذُرِّيَّتِىٓ ۖ إِنِّى تُبْتُ إِلَيْكَ وَإِنِّى مِنَ ٱلْمُسْلِمِينَ",
    transliteration: "Rabbi awzi'ni an ashkura ni'mataka allati an'amta 'alayya wa 'ala walidayya, wa an a'mala salihan tardahu, wa aslih li fi dhurriyyati, inni tubtu ilayka wa inni mina al-muslimin",
    // Al-Ahqaf 46:15 — Isa García
    translation_es: "Le he ordenado al ser humano hacer el bien a sus padres. Su madre lo ha llevado [en el vientre] con esfuerzo, y con dolor lo dio a luz. El período del embarazo y la lactancia dura treinta meses. Cuando alcance la madurez, al llegar a los cuarenta años, debe decir [en súplica]: “¡Oh, Señor mío! Haz que sepa agradecerte los favores que nos has concedido, tanto a mí como a mis padres, y que pueda realizar obras buenas que Te complazcan.",
    translation_ar: "رب أوزعني أن أشكر نعمتك وأصلح لي في ذريتي",
    translation_en: "My Lord, enable me to be grateful for Your favor, make my descendants righteous; I repent to You and I am of the Muslims.",
    source: "Al-Ahqaf 46:15",
  },
  {
    id: 'dua_ikhwan',
    title: "Perdón para los hermanos en la fe",
    title_ar: "دعاء المغفرة للإخوان",
    title_en: "Forgiveness for the brethren",
    arabic: "رَبَّنَا ٱغْفِرْ لَنَا وَلِإِخْوَٰنِنَا ٱلَّذِينَ سَبَقُونَا بِٱلْإِيمَٰنِ وَلَا تَجْعَلْ فِى قُلُوبِنَا غِلًّا لِّلَّذِينَ ءَامَنُوا۟ رَبَّنَآ إِنَّكَ رَءُوفٌ رَّحِيمٌ",
    transliteration: "Rabbana ighfir lana wa li-ikhwanina alladhina sabaquna bil-iman, wa la taj'al fi qulubina ghillan lilladhina amanu, rabbana innaka ra'ufun rahim",
    // Al-Hashr 59:10 — Isa García
    translation_es: "Quienes vienen después de ellos imploran: “¡Oh Señor nuestro! Perdónanos, a nosotros y a nuestros hermanos que nos han precedido en la fe. No infundas en nuestros corazones rencor hacia los creyentes ¡Señor nuestro!, Tú eres Compasivo, Misericordioso”.",
    translation_ar: "ربنا اغفر لنا ولإخواننا الذين سبقونا بالإيمان",
    translation_en: "Our Lord, forgive us and our brothers who preceded us in faith, and leave no rancor in our hearts toward the believers.",
    source: "Al-Hashr 59:10",
  },
  {
    id: 'dua_ibrahim_fitna',
    title: "No ser prueba para los incrédulos",
    title_ar: "دعاء السلامة من الفتنة",
    title_en: "Not to be a trial for disbelievers",
    arabic: "رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلَّذِينَ كَفَرُوا۟ وَٱغْفِرْ لَنَا رَبَّنَآ ۖ إِنَّكَ أَنتَ ٱلْعَزِيزُ ٱلْحَكِيمُ",
    transliteration: "Rabbana la taj'alna fitnatan lilladhina kafaru, waghfir lana rabbana, innaka anta al-'azizu al-hakim",
    // Al-Mumtahanah 60:5 — Isa García
    translation_es: "¡Señor nuestro! No permitas que los que se han negado a creer nos persigan, ni hagas de nosotros una causa por la cual se alejen [del Islam]. Perdónanos, ¡oh, Señor nuestro! Tú eres el Poderoso, el Sabio”.",
    translation_ar: "ربنا لا تجعلنا فتنة للذين كفروا واغفر لنا",
    translation_en: "Our Lord, do not make us a trial for those who disbelieve, and forgive us; You are the Mighty, the Wise.",
    source: "Al-Mumtahanah 60:5",
  },
  {
    id: 'dua_nur',
    title: "Para completar la luz",
    title_ar: "دعاء إتمام النور",
    title_en: "For the completion of light",
    arabic: "رَبَّنَآ أَتْمِمْ لَنَا نُورَنَا وَٱغْفِرْ لَنَآ ۖ إِنَّكَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ",
    transliteration: "Rabbana atmim lana nurana, waghfir lana, innaka 'ala kulli shay'in qadir",
    // At-Tahrim 66:8 — Isa García
    translation_es: "¡Creyentes! Arrepiéntanse sinceramente ante Dios, puede que así su Señor borre sus faltas y los introduzca en jardines del Paraíso por donde corren ríos. Ese día Dios no avergonzará al Profeta ni a los que creyeron junto a él. Una luz se extenderá delante de ellos y a su derecha, y ellos dirán: “¡Señor nuestro! Auméntanos nuestra luz y perdónanos. Tú eres sobre toda cosa poderoso”.",
    translation_ar: "ربنا أتمم لنا نورنا واغفر لنا",
    translation_en: "Our Lord, perfect our light for us and forgive us; indeed, You are over all things competent.",
    source: "At-Tahrim 66:8",
  },
  {
    id: 'dua_asiya',
    title: "Una casa en el Paraíso (Asiya)",
    title_ar: "دعاء آسية امرأة فرعون",
    title_en: "Asiya's prayer for Paradise",
    arabic: "رَبِّ ٱبْنِ لِى عِندَكَ بَيْتًا فِى ٱلْجَنَّةِ وَنَجِّنِى مِن فِرْعَوْنَ وَعَمَلِهِۦ وَنَجِّنِى مِنَ ٱلْقَوْمِ ٱلظَّٰلِمِينَ",
    transliteration: "Rabbi ibni li 'indaka baytan fil-jannah, wa najjini min fir'awna wa 'amalihi, wa najjini mina al-qawmi az-zalimin",
    // At-Tahrim 66:11 — Isa García
    translation_es: "Y para los creyentes como ejemplo plantea el caso de la mujer del Faraón [que era una verdadera creyente] cuando dijo: “¡Señor mío! Constrúyeme, junto a Ti, una morada en el Paraíso, y sálvame del Faraón y de sus obras abominables. Sálvame de este pueblo opresor”.",
    translation_ar: "رب ابن لي عندك بيتاً في الجنة",
    translation_en: "My Lord, build for me near You a house in Paradise, and save me from Pharaoh and his deeds.",
    source: "At-Tahrim 66:11",
  },
  {
    id: 'dua_nuh_parents',
    title: "Perdón para uno y sus padres",
    title_ar: "دعاء نوح للوالدين والمؤمنين",
    title_en: "Nuh's prayer for parents and believers",
    arabic: "رَبِّ ٱغْفِرْ لِى وَلِوَٰلِدَىَّ وَلِمَن دَخَلَ بَيْتِىَ مُؤْمِنًا وَلِلْمُؤْمِنِينَ وَٱلْمُؤْمِنَٰتِ",
    transliteration: "Rabbi ighfir li wa li-walidayya, wa liman dakhala baytiya mu'minan, wa lil-mu'minina wal-mu'minat",
    // Nuh 71:28 — Isa García
    translation_es: "¡Señor mío! Perdóname y perdona a mis padres, a todo aquel que ingrese a mi casa como creyente, y a todos los hombres y mujeres que crean en Ti. Pero a los injustos opresores, acreciéntales su perdición”.",
    translation_ar: "رب اغفر لي ولوالدي وللمؤمنين والمؤمنات",
    translation_en: "My Lord, forgive me and my parents and whoever enters my house a believer, and the believing men and women.",
    source: "Nuh 71:28",
  },
  {
    id: 'dua_afiya_body',
    title: "Para pedir salud y bienestar",
    title_ar: "دعاء العافية",
    title_en: "Asking for well-being",
    arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَهَ إِلَّا أَنْتَ",
    transliteration: "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i, Allahumma 'afini fi basari, la ilaha illa ant",
    // Hisnul Muslim (La Fortaleza del Musulmán) — Abu Dawud 5090
    translation_es: "Oh Dios, concédeme el bienestar en mi cuerpo, concédeme el bienestar en mi oído, concédeme el bienestar en mi vista; no hay más dios que Tú.",
    translation_ar: "اللهم عافني في بدني وسمعي وبصري",
    translation_en: "O Allah, grant me well-being in my body, my hearing and my sight; there is no god but You.",
    source: "Abu Dawud 5090",
  },
  {
    id: 'dua_huda_tuqa',
    title: "Guía, piedad y suficiencia",
    title_ar: "دعاء الهدى والتقى والعفاف والغنى",
    title_en: "Guidance, piety and sufficiency",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى",
    transliteration: "Allahumma inni as'aluka al-huda wat-tuqa, wal-'afafa wal-ghina",
    // Hisnul Muslim (La Fortaleza del Musulmán) — Muslim 2721
    translation_es: "Oh Dios, Te pido la guía, la piedad, la castidad y la suficiencia.",
    translation_ar: "اللهم إني أسألك الهدى والتقى والعفاف والغنى",
    translation_en: "O Allah, I ask You for guidance, piety, chastity and self-sufficiency.",
    source: "Muslim 2721",
  },
  {
    id: 'dua_din_dunya',
    title: "Para enmendar la religión y la vida",
    title_ar: "دعاء إصلاح الدين والدنيا",
    title_en: "Rectifying religion and life",
    arabic: "اللَّهُمَّ أَصْلِحْ لِي دِينِي الَّذِي هُوَ عِصْمَةُ أَمْرِي، وَأَصْلِحْ لِي دُنْيَايَ الَّتِي فِيهَا مَعَاشِي، وَأَصْلِحْ لِي آخِرَتِي الَّتِي فِيهَا مَعَادِي، وَاجْعَلِ الْحَيَاةَ زِيَادَةً لِي فِي كُلِّ خَيْرٍ، وَاجْعَلِ الْمَوْتَ رَاحَةً لِي مِنْ كُلِّ شَرٍّ",
    transliteration: "Allahumma aslih li dini alladhi huwa 'ismatu amri, wa aslih li dunyaya allati fiha ma'ashi, wa aslih li akhirati allati fiha ma'adi, waj'ali al-hayata ziyadatan li fi kulli khayr, waj'ali al-mawta rahatan li min kulli sharr",
    // Hisnul Muslim (La Fortaleza del Musulmán) — Muslim 2720
    translation_es: "Oh Dios, enmiéndame mi religión, que es la protección de mi asunto; enmiéndame mi vida terrenal, en la que está mi sustento; enmiéndame mi otra vida, a la que es mi retorno; haz que la vida sea para mí un aumento en todo bien, y que la muerte sea un alivio de todo mal.",
    translation_ar: "اللهم أصلح لي ديني ودنياي وآخرتي",
    translation_en: "O Allah, set right my religion, my worldly life and my Hereafter; make life an increase in all good and death a relief from all evil.",
    source: "Muslim 2720",
  },
  {
    id: 'dua_qunut',
    title: "Del qunut: guía y protección",
    title_ar: "دعاء القنوت",
    title_en: "The qunut supplication",
    arabic: "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ، وَبَارِكْ لِي فِيمَا أَعْطَيْتَ، وَقِنِي شَرَّ مَا قَضَيْتَ",
    transliteration: "Allahumma ihdini fiman hadayt, wa 'afini fiman 'afayt, wa tawallani fiman tawallayt, wa barik li fima a'tayt, wa qini sharra ma qadayt",
    // Hisnul Muslim (La Fortaleza del Musulmán) — Abu Dawud 1425, At-Tirmidhi 464
    translation_es: "Oh Dios, guíame entre aquellos a quienes has guiado, concédeme el bienestar entre aquellos a quienes lo has concedido, protégeme entre aquellos a quienes has protegido, bendíceme en lo que me has dado y guárdame del mal que has decretado.",
    translation_ar: "اللهم اهدني فيمن هديت وعافني فيمن عافيت",
    translation_en: "O Allah, guide me among those You have guided, grant me well-being among those You have granted it, and protect me from the evil You have decreed.",
    source: "Abu Dawud 1425, At-Tirmidhi 464",
  },
  {
    id: 'dua_niama',
    title: "Refugio ante la pérdida de las bendiciones",
    title_ar: "دعاء حفظ النعم",
    title_en: "Preserving the blessings",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ زَوَالِ نِعْمَتِكَ، وَتَحَوُّلِ عَافِيَتِكَ، وَفُجَاءَةِ نِقْمَتِكَ، وَجَمِيعِ سَخَطِكَ",
    transliteration: "Allahumma inni a'udhu bika min zawali ni'matik, wa tahawwuli 'afiyatik, wa fuja'ati niqmatik, wa jami'i sakhatik",
    // Hisnul Muslim (La Fortaleza del Musulmán) — Muslim 2739
    translation_es: "Oh Dios, me refugio en Ti de la desaparición de Tu favor, del cambio del bienestar que me concedes, de la llegada repentina de Tu castigo y de todo lo que provoque Tu ira.",
    translation_ar: "اللهم إني أعوذ بك من زوال نعمتك",
    translation_en: "O Allah, I seek refuge in You from the removal of Your blessing, the loss of well-being, Your sudden punishment and all that earns Your displeasure.",
    source: "Muslim 2739",
  },
  {
    id: 'dua_tazkiya_nafs',
    title: "Para purificar el alma",
    title_ar: "دعاء تزكية النفس",
    title_en: "Purifying the soul",
    arabic: "اللَّهُمَّ آتِ نَفْسِي تَقْوَاهَا، وَزَكِّهَا أَنْتَ خَيْرُ مَنْ زَكَّاهَا، أَنْتَ وَلِيُّهَا وَمَوْلَاهَا",
    transliteration: "Allahumma ati nafsi taqwaha, wa zakkiha anta khayru man zakkaha, anta waliyyuha wa mawlaha",
    // Hisnul Muslim (La Fortaleza del Musulmán) — Muslim 2722
    translation_es: "Oh Dios, concede a mi alma su piedad y purifícala, pues Tú eres el mejor para purificarla; Tú eres su Protector y su Dueño.",
    translation_ar: "اللهم آت نفسي تقواها وزكها",
    translation_en: "O Allah, grant my soul its piety and purify it; You are the best to purify it, its Protector and Master.",
    source: "Muslim 2722",
  },
  {
    id: 'dua_nur_samawat',
    title: "Alabanza al abrir la oración nocturna",
    title_ar: "دعاء استفتاح صلاة الليل",
    title_en: "Opening the night prayer",
    arabic: "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ نُورُ السَّمَاوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ، وَلَكَ الْحَمْدُ أَنْتَ قَيِّمُ السَّمَاوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ، وَلَكَ الْحَمْدُ أَنْتَ الْحَقُّ، وَوَعْدُكَ حَقٌّ، وَلِقَاؤُكَ حَقٌّ",
    transliteration: "Allahumma laka al-hamdu anta nuru as-samawati wal-ardi wa man fihinn, wa laka al-hamdu anta qayyimu as-samawati wal-ardi wa man fihinn, wa laka al-hamdu anta al-haqqu, wa wa'duka haqqun, wa liqa'uka haqq",
    // Hisnul Muslim (La Fortaleza del Musulmán) — Muslim 769
    translation_es: "Oh Dios, Tuya es la alabanza; Tú eres la luz de los cielos y de la tierra y de quienes habitan en ellos. Tuya es la alabanza; Tú eres el Sustentador de los cielos y de la tierra y de quienes habitan en ellos. Tuya es la alabanza; Tú eres la Verdad, Tu promesa es verdadera y el encuentro Contigo es verdadero.",
    translation_ar: "اللهم لك الحمد أنت نور السماوات والأرض",
    translation_en: "O Allah, to You belongs all praise; You are the Light of the heavens and the earth and whoever is in them.",
    source: "Muslim 769",
  },
];

function getDuaOfTheDay() {
  const today = new Date();
  const day = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 86400000);
  return DAILY_DUAS[day % DAILY_DUAS.length];
}
