// 🤲 Du'as curadas — "Du'a del día"
// v36: Traducciones españolas REVISADAS y sustituidas por versiones de fuentes
//      acreditadas (ya no traducciones literales improvisadas):
//   • Du'as coránicas → Traducción comentada del Corán, Lic. M. Isa García
//     (misma fuente oficial que usa la app para las aleyas: data/garcia/*.json).
//   • Du'as de hadiz → traducción española estándar publicada de
//     "La Fortaleza del Musulmán" (Hisnul Muslim, ed. Darussalam).
//   • NUEVO: campo translation_ar con el texto árabe completo, para que la
//     interfaz en árabe muestre el du'a correcto (antes se mostraba español).
const DAILY_DUAS = [
  {
    id: 'morning_1',
    title: "Du'a de la mañana",
    title_ar: 'دعاء الصباح',
    title_en: 'Morning supplication',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
    transliteration: 'Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namutu, wa ilayka an-nushur',
    translation_es: 'Oh Dios, por Ti llegamos a la mañana, por Ti llegamos a la tarde, por Ti vivimos y por Ti morimos, y hacia Ti es la resurrección.',
    translation_ar: 'اللهم بك أصبحنا، وبك أمسينا، وبك نحيا، وبك نموت، وإليك النشور',
    translation_en: 'O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.',
    source: 'At-Tirmidhi 3391',
  },
  {
    id: 'guidance_1',
    title: 'Para pedir guía',
    title_ar: 'دعاء طلب الهداية',
    title_en: 'Asking for guidance',
    arabic: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ',
    transliteration: 'Ihdina as-sirat al-mustaqim',
    // Al-Fatihah 1:6 — Isa García
    translation_es: '¡Guíanos por el camino recto!',
    translation_ar: 'اهدنا الصراط المستقيم',
    translation_en: 'Guide us along the straight path.',
    source: 'Al-Fatihah 1:6',
  },
  {
    id: 'forgiveness_1',
    title: 'Para pedir perdón',
    title_ar: 'دعاء طلب المغفرة',
    title_en: 'Asking for forgiveness',
    arabic: 'رَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ',
    transliteration: 'Rabbana zalamna anfusana wa in lam taghfir lana wa tarhamna lanakunanna min al-khasirin',
    // Al-A'raf 7:23 — Isa García
    translation_es: '¡Señor nuestro! Hemos sido injustos con nosotros mismos; si no nos perdonas y nos tienes misericordia, seremos de los perdidos.',
    translation_ar: 'ربنا ظلمنا أنفسنا وإن لم تغفر لنا وترحمنا لنكونن من الخاسرين',
    translation_en: 'Our Lord, we have wronged ourselves; if You do not forgive us and have mercy upon us, we will surely be among the losers.',
    source: "Al-A'raf 7:23",
  },
  {
    id: 'knowledge_1',
    title: 'Para pedir conocimiento útil',
    title_ar: 'دعاء طلب العلم النافع',
    title_en: 'Asking for beneficial knowledge',
    arabic: 'رَبِّ زِدْنِي عِلْمًا',
    transliteration: "Rabbi zidni 'ilman",
    // Ta-Ha 20:114 — Isa García
    translation_es: '¡Oh, Señor mío! Increméntame en conocimiento.',
    translation_ar: 'رب زدني علما',
    translation_en: 'My Lord, increase me in knowledge.',
    source: 'Ta-Ha 20:114',
  },
  {
    id: 'parents_1',
    title: 'Por los padres',
    title_ar: 'الدعاء للوالدين',
    title_en: 'For the parents',
    arabic: 'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    transliteration: 'Rabbi-rhamhuma kama rabbayani saghira',
    // Al-Isra 17:24 — Isa García
    translation_es: '¡Oh, Señor mío! Ten misericordia de ellos como ellos la tuvieron conmigo cuando me criaron siendo niño.',
    translation_ar: 'رب ارحمهما كما ربياني صغيرا',
    translation_en: 'My Lord, have mercy upon them as they raised me when I was small.',
    source: 'Al-Isra 17:24',
  },
  {
    id: 'protection_1',
    title: 'Protección al salir de casa',
    title_ar: 'دعاء الخروج من المنزل',
    title_en: 'When leaving the house',
    arabic: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: "Bismillah, tawakkaltu 'ala Allah, wa la hawla wa la quwwata illa billah",
    // Hisnul Muslim — traducción española publicada (Darussalam)
    translation_es: 'En el nombre de Dios, en Dios confío, y no hay poder ni fuerza excepto en Dios.',
    translation_ar: 'بسم الله، توكلت على الله، ولا حول ولا قوة إلا بالله',
    translation_en: 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
    source: 'Abu Dawud 5095, At-Tirmidhi 3426',
  },
  {
    id: 'anxiety_1',
    title: 'Para alivio de la ansiedad',
    title_ar: 'دعاء تفريج الهم',
    title_en: 'For relief from anxiety',
    arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: "Hasbuna Allah wa ni'ma al-wakil",
    // Al-i'Imran 3:173 — Isa García
    translation_es: 'Dios es suficiente para nosotros, porque Él es el mejor protector.',
    translation_ar: 'حسبنا الله ونعم الوكيل',
    translation_en: 'Allah is sufficient for us, and He is the best Disposer of affairs.',
    source: "Al-i'Imran 3:173",
  },

  // ================================================================
  // v36: Expansión de la base de du'as del día — du'as auténticos y
  // conocidos, con sabiduría y lección. Traducciones españolas de fuentes
  // acreditadas: las coránicas según Isa García (data/garcia) y las de
  // hadiz según la traducción publicada de La Fortaleza del Musulmán.
  // ================================================================
  {
    id: 'sayyid_istighfar_day',
    title: 'Sayyid al-Istighfar (la mejor súplica de perdón)',
    title_ar: 'سيد الاستغفار',
    title_en: 'Sayyid al-Istighfar (the chief supplication for forgiveness)',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: "Allahumma anta Rabbi, la ilaha illa Ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayya, wa abu'u bidhanbi, faghfir li fa innahu la yaghfirudh-dhunuba illa Ant",
    translation_es: 'Oh Dios, Tú eres mi Señor, no hay otra divinidad sino Tú. Tú me creaste y yo soy Tu siervo, y me comprometo a cumplir Tu pacto y Tu promesa en la medida de mis posibilidades. Me refugio en Ti del mal que he cometido. Reconozco Tus bendiciones sobre mí y reconozco mis pecados; perdóname, pues nadie perdona los pecados excepto Tú.',
    translation_ar: 'اللهم أنت ربي لا إله إلا أنت، خلقتني وأنا عبدك، وأنا على عهدك ووعدك ما استطعت، أعوذ بك من شر ما صنعت، أبوء لك بنعمتك علي، وأبوء بذنبي، فاغفر لي فإنه لا يغفر الذنوب إلا أنت',
    translation_en: 'O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant; I abide by Your covenant and Your promise as best I can. I seek refuge with You from the evil I have committed. I acknowledge Your favor upon me and I acknowledge my sins; forgive me, for none forgives sins but You.',
    source: 'Al-Bujari 6306',
  },
  {
    id: 'rabban_atina_day',
    title: 'La súplica más completa',
    title_ar: 'الدعاء الجامع — ربنا آتنا في الدنيا حسنة',
    title_en: 'The most comprehensive supplication',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: "Rabbana atina fid-dunya hasanah, wa fil-akhirati hasanah, wa qina 'adhab an-nar",
    // Al-Baqarah 2:201 — Isa García
    translation_es: '¡Señor nuestro! Danos bienestar en esta vida y en la otra, y presérvanos del tormento del Fuego.',
    translation_ar: 'ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار',
    translation_en: 'Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.',
    source: 'Al-Baqarah 2:201',
  },
  {
    id: 'sayyid_shafa_day',
    title: "Du'a de la curación",
    title_ar: 'دعاء الشفاء',
    title_en: 'Supplication for healing',
    arabic: 'اللَّهُمَّ رَبَّ النَّاسِ، أَذْهِبِ الْبَأْسَ، اشْفِ أَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا',
    transliteration: "Allahumma Rabban-nas, adhhib al-ba's, ishfi Antash-Shafi, la shifa'a illa shifa'uk, shifa'an la yughadiru saqama",
    translation_es: 'Oh Dios, Señor de los hombres, aleja el mal y cura, pues Tú eres el Sanador. No hay curación sino la Tuya: una curación que no deja enfermedad alguna.',
    translation_ar: 'اللهم رب الناس، أذهب البأس، اشف أنت الشافي، لا شفاء إلا شفاؤك، شفاء لا يغادر سقما',
    translation_en: 'O Allah, Lord of mankind, remove the harm and heal, for You are the Healer. There is no healing except Your healing — a healing that leaves no illness behind.',
    source: 'Al-Bujari 5675, Muslim 2191',
  },
  {
    id: 'rizq_halal_day',
    title: 'Suficiencia en lo lícito',
    title_ar: 'دعاء الكفاف بالحلال',
    title_en: 'Sufficiency through the lawful',
    arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    transliteration: "Allahumma-kfini bihalalika 'an haramik, wa aghnini bifadlika 'amman siwak",
    translation_es: 'Oh Dios, bástame con lo lícito que me has permitido en lugar de lo ilícito que me has prohibido, y enriquéceme con Tu favor de modo que no necesite a nadie más que a Ti.',
    translation_ar: 'اللهم اكفني بحلالك عن حرامك، وأغنني بفضلك عمن سواك',
    translation_en: 'O Allah, suffice me with Your lawful against Your unlawful, and enrich me by Your bounty from all besides You.',
    source: 'At-Tirmidhi 3563',
  },
  {
    id: 'hamm_hazan_day',
    title: 'Contra la preocupación y la tristeza',
    title_ar: 'دعاء الهم والحزن',
    title_en: 'Against worry and sorrow',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan, wal-'ajzi wal-kasal, wal-bukhli wal-jubn, wa dala'id-dayni wa ghalabatir-rijal",
    translation_es: 'Oh Dios, me refugio en Ti de la preocupación y la tristeza, de la incapacidad y la pereza, de la avaricia y la cobardía, y del peso de las deudas y la opresión de los hombres.',
    translation_ar: 'اللهم إني أعوذ بك من الهم والحزن، والعجز والكسل، والبخل والجبن، وضلع الدين وغلبة الرجال',
    translation_en: 'O Allah, I seek refuge in You from worry and sorrow, from incapacity and laziness, from miserliness and cowardice, and from the burden of debts and the overpowering of men.',
    source: 'Al-Bujari 6369',
  },
  {
    id: 'knowledge_beneficial_day',
    title: 'Conocimiento beneficioso y buen sustento',
    title_ar: 'دعاء العلم النافع والرزق الطيب',
    title_en: 'Beneficial knowledge and good provision',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
    transliteration: "Allahumma inni as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbala",
    translation_es: 'Oh Dios, Te pido un conocimiento beneficioso, un sustento bueno y lícito, y obras que Te sean aceptadas.',
    translation_ar: 'اللهم إني أسألك علما نافعا، ورزقا طيبا، وعملا متقبلا',
    translation_en: 'O Allah, I ask You for beneficial knowledge, good and lawful provision, and deeds that are accepted.',
    source: 'Ibn Majah 925',
  },
  {
    id: 'allahumma_ainni_day',
    title: 'Ayuda para recordar y agradecer',
    title_ar: 'دعاء طلب الإعانة على الذكر والشكر',
    title_en: 'Help in remembrance and gratitude',
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ، وَشُكْرِكَ، وَحُسْنِ عِبَادَتِكَ',
    transliteration: "Allahumma a'inni 'ala dhikrika, wa shukrika, wa husni 'ibadatik",
    translation_es: 'Oh Dios, ayúdame a recordarte, a agradecerte y a adorarte de la mejor manera.',
    translation_ar: 'اللهم أعني على ذكرك، وشكرك، وحسن عبادتك',
    translation_en: 'O Allah, help me to remember You, to thank You, and to worship You in the best manner.',
    source: 'Abu Dawud 1522',
  },
  {
    id: 'istighfar_tawba_day',
    title: 'Perdón y regreso a Dios',
    title_ar: 'دعاء الاستغفار والتوبة',
    title_en: 'Forgiveness and repentance',
    arabic: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيَّ الْقَيُّومَ وَأَتُوبُ إِلَيْهِ',
    transliteration: "Astaghfirullah al-'Adhim alladhi la ilaha illa Huwa al-Hayyul-Qayyum, wa atubu ilayh",
    translation_es: 'Pido perdón a Dios el Magnífico, no hay otra divinidad sino Él, el Viviente, el Sustentador, y a Él me retorno arrepentido.',
    translation_ar: 'أستغفر الله العظيم الذي لا إله إلا هو الحي القيوم وأتوب إليه',
    translation_en: 'I seek the forgiveness of Allah the Magnificent, besides Whom there is no god, the Living, the Sustainer, and I repent to Him.',
    source: 'Abu Dawud 1517, At-Tirmidhi 3577',
  },
  {
    id: 'ya_hayyu_day',
    title: 'Ya Hayyu ya Qayyum',
    title_ar: 'يا حي يا قيوم',
    title_en: 'O Ever-Living, O Sustainer',
    arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ',
    transliteration: "Ya Hayyu ya Qayyum, birahmatika astaghith, aslih li sha'ni kullahu, wa la takilni ila nafsi tarfata 'ayn",
    translation_es: '¡Oh Viviente, oh Sustentador! Imploro auxilio por Tu misericordia. Dispón todos mis asuntos y no me dejes a cargo de mí mismo ni un abrir y cerrar de ojos.',
    translation_ar: 'يا حي يا قيوم برحمتك أستغيث، أصلح لي شأني كله، ولا تكلني إلى نفسي طرفة عين',
    translation_en: 'O Ever-Living, O Sustainer, by Your mercy I seek assistance. Set right all of my affairs, and do not leave me to myself even for the blink of an eye.',
    source: 'At-Tirmidhi 3524',
  },
  {
    id: 'dunia_day',
    title: 'Que la vida mundanal no sea nuestra mayor preocupación',
    title_ar: 'دعاء ألا تكون الدنيا أكبر همنا',
    title_en: 'That this world not be our greatest concern',
    arabic: 'اللَّهُمَّ لَا تَجْعَلِ الدُّنْيَا أَكْبَرَ هَمِّنَا، وَلَا مَبْلَغَ عِلْمِنَا، وَلَا إِلَى النَّارِ مَصِيرَنَا، وَاجْعَلِ الْجَنَّةَ هِيَ دَارَنَا',
    transliteration: "Allahumma la taj'alid-dunya akbara hammina, wa la mablagha 'ilmina, wa la ilan-nari masirana, waj'alil-jannata hiya darana",
    translation_es: 'Oh Dios, no hagas que la vida mundanal sea nuestra mayor preocupación ni el límite de nuestro conocimiento, ni que el Fuego sea nuestro destino, y haz que el Paraíso sea nuestra morada.',
    translation_ar: 'اللهم لا تجعل الدنيا أكبر همنا، ولا مبلغ علمنا، ولا إلى النار مصيرنا، واجعل الجنة هي دارنا',
    translation_en: 'O Allah, do not make this world our greatest concern nor the limit of our knowledge, nor the Fire our destination, and make Paradise our abode.',
    source: 'At-Tabarani, Al-Mu\'yam al-Awsat 4774',
  },
  {
    id: 'salat_nabi_day',
    title: 'Bendiciones sobre el Profeta ﷺ',
    title_ar: 'الصلاة على النبي ﷺ',
    title_en: 'Blessings upon the Prophet ﷺ',
    arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ',
    transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad",
    translation_es: 'Oh Dios, bendice a Mujámmad y a la familia de Mujámmad.',
    translation_ar: 'اللهم صل على محمد وعلى آل محمد',
    translation_en: 'O Allah, send Your blessings upon Muhammad and upon the family of Muhammad.',
    source: 'Al-Bujari 3370, Muslim 406',
  },
  // ---- Du'as coránicas de los profetas (Isa García) ----
  {
    id: 'dua_nuh_day',
    title: "Du'a de Nuh عليه السلام",
    title_ar: 'دعاء نوح عليه السلام',
    title_en: "Supplication of Noah, peace be upon him",
    arabic: 'أَنِّي مَغْلُوبٌ فَانتَصِرْ',
    transliteration: 'Anni maghlubun fantasir',
    // Al-Qamar 54:10 — Isa García
    translation_es: '¡Me han vencido, Te pido ayuda!',
    translation_ar: 'أني مغلوب فانتصر',
    translation_en: 'I have been overcome, so help me!',
    source: 'Al-Qamar 54:10',
  },
  {
    id: 'dua_ayyub_day',
    title: "Du'a de Ayyub عليه السلام (paciencia en la enfermedad)",
    title_ar: 'دعاء أيوب عليه السلام',
    title_en: "Supplication of Job, peace be upon him",
    arabic: 'أَنِّي مَسَّنِيَ الضُّرُّ وَأَنْتَ أَرْحَمُ الرَّاحِمِينَ',
    transliteration: "Anni massaniyad-durru wa Anta arhamur-rahimin",
    // Al-Anbiya 21:83 — Isa García
    translation_es: 'He sido probado con enfermedades, pero Tú eres el más Misericordioso.',
    translation_ar: 'أني مسني الضر وأنت أرحم الراحمين',
    translation_en: 'Indeed, adversity has touched me, and You are the Most Merciful of the merciful.',
    source: 'Al-Anbiya 21:83',
  },
  {
    id: 'dua_musa_need_day',
    title: "Du'a de Musa عليه السلام ante la necesidad",
    title_ar: 'دعاء موسى عليه السلام عند الحاجة',
    title_en: "Supplication of Moses in need",
    arabic: 'رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ',
    transliteration: "Rabbi inni lima anzalta ilayya min khayrin faqir",
    // Al-Qasas 28:24 — Isa García
    translation_es: '¡Señor mío! Realmente necesito cualquier gracia que me concedas.',
    translation_ar: 'رب إني لما أنزلت إلي من خير فقير',
    translation_en: 'My Lord, indeed I am, for whatever good You would send down to me, in need.',
    source: 'Al-Qasas 28:24',
  },
  {
    id: 'dua_yunus_day',
    title: "Du'a de Yunus عليه السلام (alivio de toda angustia)",
    title_ar: 'دعاء يونس عليه السلام',
    title_en: "Supplication of Jonah, peace be upon him",
    arabic: 'لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',
    transliteration: 'La ilaha illa Anta, subhanaka, inni kuntu minaz-zalimin',
    // Al-Anbiya 21:87 — Isa García
    translation_es: 'No hay otra divinidad más que Tú. ¡Glorificado seas! En verdad he sido de los injustos.',
    translation_ar: 'لا إله إلا أنت سبحانك إني كنت من الظالمين',
    translation_en: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
    source: 'Al-Anbiya 21:87',
  },
  {
    id: 'dua_ibrahim_child_day',
    title: "Du'a de Ibrahim عليه السلام por la descendencia",
    title_ar: 'دعاء إبراهيم عليه السلام للذرية',
    title_en: "Supplication of Abraham for offspring",
    arabic: 'رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ',
    transliteration: 'Rabbi hab li minas-salihin',
    // As-Saffat 37:100 — Isa García
    translation_es: '¡Oh, Señor mío! Concédeme un hijo justo.',
    translation_ar: 'رب هب لي من الصالحين',
    translation_en: 'My Lord, grant me a righteous son.',
    source: 'As-Saffat 37:100',
  },
];

function getDuaOfTheDay() {
  const today = new Date();
  const day = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 86400000);
  return DAILY_DUAS[day % DAILY_DUAS.length];
}
