// 📄 PrayerPdf — Exportación de horarios de oración a PDF (100% cliente)
//
// Genera un PDF A4 con el logo de la app (Quba) y el logo de la mezquita,
// tanto para las oraciones del día como para la tabla del mes completo.
//
// Técnica: se dibuja el documento en un <canvas> offscreen (así el texto
// árabe se renderiza con el shaping nativo del navegador y las fuentes
// Amiri/Noto Naskh ya cargadas por la app) y se inserta como imagen en un
// PDF A4 mediante jsPDF (cargado desde cdnjs, permitido por la CSP).
const PrayerPdf = {
  // Identidad visual (mismos tokens que el calendario v16)
  COLORS: {
    green: '#0F4C3A',
    greenDark: '#0A3528',
    gold: '#D4AF37',
    navy: '#0d2b4e',
    ink: '#1f2937',
    muted: '#6b7280',
    rowAlt: '#f3f7f5',
    friday: '#fdf6e3',
    today: '#e7f4ec',
    line: '#d9e2dd',
  },

  // A4 vertical a 150 DPI
  PAGE_W: 1240,
  PAGE_H: 1754,

  _logoCache: {},

  // Carga una imagen local como HTMLImageElement (con caché)
  _loadImage(src) {
    if (this._logoCache[src]) return this._logoCache[src];
    this._logoCache[src] = new Promise((resolve) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => resolve(null);
      img.src = src;
    });
    return this._logoCache[src];
  },

  _lang() {
    return (typeof currentLocale !== 'undefined' && currentLocale === 'ar')
      ? 'ar' : (currentLocale === 'en' ? 'en' : 'es');
  },

  // Textos trilingües del PDF (no dependen de i18n para no romper nada)
  _L(key) {
    const lang = this._lang();
    const T = {
      appTagline:   { es: 'Tu compañero hacia el Paraíso, si Dios quiere', ar: 'رفيقك إلى الجنة بإذن الله', en: 'Your companion to Paradise, God willing' },
      dailyTitle:   { es: 'Oraciones de hoy',               ar: 'صلوات اليوم',               en: "Today's Prayers" },
      monthTitle:   { es: 'Horario de oraciones del mes',   ar: 'جدول صلوات الشهر',          en: 'Monthly Prayer Schedule' },
      adhan:        { es: 'Adhan',                          ar: 'الأذان',                    en: 'Adhan' },
      iqamah:       { es: 'Iqamah',                         ar: 'الإقامة',                   en: 'Iqamah' },
      day:          { es: 'Día',                            ar: 'اليوم',                     en: 'Day' },
      prayer:       { es: 'Oración',                        ar: 'الصلاة',                    en: 'Prayer' },
      generated:    { es: 'Generado por la app Quba',       ar: 'صادر عن تطبيق قبة',        en: 'Generated by the Quba app' },
      friday:       { es: 'Viernes',                        ar: 'الجمعة',                    en: 'Friday' },
      today:        { es: 'Hoy',                            ar: 'اليوم',                     en: 'Today' },
      sunrise:      { es: 'Amanecer',                       ar: 'الشروق',                    en: 'Sunrise' },
    };
    return (T[key] && T[key][lang]) || key;
  },

  _prayerName(name) {
    const base = (typeof t === 'function' ? t('prayers.' + name) : '') || name;
    return base;
  },

  _prayerArabic(name) {
    if (typeof HomePage !== 'undefined' && typeof HomePage.prayerArabic === 'function') {
      try { const v = HomePage.prayerArabic(name); if (v) return v; } catch (e) {}
    }
    return { Fajr: 'الفجر', Sunrise: 'الشروق', Dhuhr: 'الظهر', Asr: 'العصر', Maghrib: 'المغرب', Isha: 'العشاء' }[name] || '';
  },

  _fmt(time24) {
    if (!time24 || !time24.includes(':')) return '--:--';
    if (this._lang() === 'ar') return time24; // 24h para árabe
    return (typeof formatTime12h === 'function') ? formatTime12h(time24) : time24;
  },

  _t24(v) { return (v || '').split(' ')[0].slice(0, 5); },

  _hijriLine() {
    const h = (typeof AppState !== 'undefined') ? AppState.hijri : null;
    if (!h) return '';
    const lang = this._lang();
    const month = (lang === 'ar') ? (h.month?.ar || h.month?.en || '') : (h.month?.en || '');
    return `${h.day} ${month} ${h.year} هـ`;
  },

  _locationLine() {
    const loc = (typeof AppState !== 'undefined') ? AppState.location : null;
    if (!loc) return '';
    return [loc.city, loc.country].filter(Boolean).join(', ');
  },

  // Dibuja una imagen recortada en círculo
  _drawCircleImage(ctx, img, cx, cy, r, ringColor) {
    ctx.save();
    ctx.beginPath();
    ctx.arc(cx, cy, r, 0, Math.PI * 2);
    ctx.closePath();
    ctx.fillStyle = '#ffffff';
    ctx.fill();
    if (img) {
      ctx.clip();
      // cover
      const s = Math.min(img.width, img.height);
      const sw = s, sh = s;
      const sx = (img.width - s) / 2, sy = (img.height - s) / 2;
      ctx.drawImage(img, sx, sy, sw, sh, cx - r, cy - r, r * 2, r * 2);
    }
    ctx.restore();
    // anillo dorado
    ctx.beginPath();
    ctx.arc(cx, cy, r, 0, Math.PI * 2);
    ctx.lineWidth = 6;
    ctx.strokeStyle = ringColor || this.COLORS.gold;
    ctx.stroke();
  },

  // Cabecera común: banda verde + dos logos + títulos
  async _drawHeader(ctx, title) {
    const C = this.COLORS, W = this.PAGE_W;
    const [appLogo, mosqueLogo] = await Promise.all([
      this._loadImage('assets/logo.png'),
      this._loadImage('assets/mosque-logo.png'),
    ]);

    // Banda superior
    const headerH = 300;
    const grad = ctx.createLinearGradient(0, 0, 0, headerH);
    grad.addColorStop(0, C.green);
    grad.addColorStop(1, C.greenDark);
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, W, headerH);
    // Filete dorado inferior
    ctx.fillStyle = C.gold;
    ctx.fillRect(0, headerH, W, 8);

    // Logos en círculo (izquierda: app, derecha: mezquita)
    this._drawCircleImage(ctx, appLogo, 140, 150, 92, C.gold);
    this._drawCircleImage(ctx, mosqueLogo, W - 140, 150, 92, C.gold);

    // Título central
    ctx.textAlign = 'center';
    ctx.fillStyle = '#ffffff';
    ctx.font = '700 64px Amiri, "Noto Naskh Arabic", serif';
    ctx.fillText('Quba — قبة', W / 2, 118);

    ctx.font = '700 52px Amiri, "Noto Naskh Arabic", serif';
    ctx.fillStyle = C.gold;
    ctx.fillText(title, W / 2, 196);

    // Línea de ubicación + fecha hijri
    const meta = [this._locationLine(), this._hijriLine()].filter(Boolean).join('  ·  ');
    if (meta) {
      ctx.font = '400 30px Inter, Amiri, "Noto Naskh Arabic", sans-serif';
      ctx.fillStyle = 'rgba(255,255,255,0.92)';
      ctx.fillText(meta, W / 2, 250);
    }

    return headerH + 8; // y donde empieza el contenido
  },

  _drawFooter(ctx) {
    const C = this.COLORS, W = this.PAGE_W, H = this.PAGE_H;
    ctx.fillStyle = C.line;
    ctx.fillRect(80, H - 110, W - 160, 2);
    ctx.textAlign = 'center';
    ctx.font = '400 26px Inter, Amiri, "Noto Naskh Arabic", sans-serif';
    ctx.fillStyle = C.muted;
    const stamp = new Date().toLocaleDateString(
      this._lang() === 'ar' ? 'ar-EG' : this._lang(),
      { year: 'numeric', month: 'long', day: 'numeric' }
    );
    ctx.fillText(`${this._L('generated')} · ${stamp}`, W / 2, H - 66);
    ctx.fillStyle = C.gold;
    ctx.font = '700 26px Amiri, "Noto Naskh Arabic", serif';
    ctx.fillText('﷽', W / 2, H - 28);
  },

  // Se asegura de que jsPDF esté cargado. Si la librería local no se cargó
  // (p. ej. caché antigua), la inyecta dinámicamente desde js/vendor.
  async _ensureJsPdf() {
    if (window.jspdf && window.jspdf.jsPDF) return;
    await new Promise((resolve, reject) => {
      const s = document.createElement('script');
      s.src = 'js/vendor/jspdf.umd.min.js';
      s.onload = resolve;
      s.onerror = () => reject(new Error('jspdf no disponible'));
      document.head.appendChild(s);
    });
    if (!window.jspdf || !window.jspdf.jsPDF) throw new Error('jspdf no disponible');
  },

  // Convierte el canvas en un PDF A4 y lo descarga
  _save(canvas, filename) {
    const { jsPDF } = window.jspdf;
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const img = canvas.toDataURL('image/jpeg', 0.92);
    pdf.addImage(img, 'JPEG', 0, 0, 210, 297);
    pdf.save(filename);
  },

  _newCanvas() {
    const canvas = document.createElement('canvas');
    canvas.width = this.PAGE_W;
    canvas.height = this.PAGE_H;
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, this.PAGE_W, this.PAGE_H);
    return { canvas, ctx };
  },

  _busy(btn, on) {
    if (!btn) return;
    btn.disabled = on;
    btn.classList.toggle('is-loading', on);
  },

  // ============ PDF DEL DÍA ============
  async downloadDaily(btn) {
    this._busy(btn, true);
    try {
      await this._ensureJsPdf();
      if (document.fonts && document.fonts.ready) await document.fonts.ready;
      const timings = (typeof AppState !== 'undefined') && AppState.timings;
      if (!timings) throw new Error('no timings');
      const prayers = (typeof getDailyPrayers === 'function') ? getDailyPrayers(timings) : [];
      const next = (typeof getNextPrayer === 'function') ? getNextPrayer(timings) : null;

      const { canvas, ctx } = this._newCanvas();
      const C = this.COLORS, W = this.PAGE_W;
      let y = await this._drawHeader(ctx, this._L('dailyTitle'));

      // Tabla
      const x0 = 90, x1 = W - 90;
      const rowH = 130, headH = 78;
      const cols = this._lang() === 'ar'
        ? [ { w: 0.34, k: 'prayer' }, { w: 0.33, k: 'adhan' }, { w: 0.33, k: 'iqamah' } ]
        : [ { w: 0.34, k: 'prayer' }, { w: 0.33, k: 'adhan' }, { w: 0.33, k: 'iqamah' } ];

      // Cabecera de tabla
      ctx.fillStyle = C.navy;
      ctx.fillRect(x0, y, x1 - x0, headH);
      ctx.textAlign = 'center';
      ctx.font = '700 32px Inter, Amiri, "Noto Naskh Arabic", sans-serif';
      ctx.fillStyle = '#ffffff';
      let cx = x0;
      cols.forEach(c => {
        const cw = (x1 - x0) * c.w;
        ctx.fillText(this._L(c.k), cx + cw / 2, y + headH / 2 + 11);
        cx += cw;
      });
      y += headH;

      // Filas
      prayers.forEach((p, i) => {
        const isNext = next && next.name === p.name;
        ctx.fillStyle = isNext ? C.today : (i % 2 ? C.rowAlt : '#ffffff');
        ctx.fillRect(x0, y, x1 - x0, rowH);
        if (isNext) { // borde dorado a la próxima oración
          ctx.fillStyle = C.gold;
          ctx.fillRect(x0, y, 8, rowH);
        }
        ctx.strokeStyle = C.line;
        ctx.lineWidth = 1.5;
        ctx.strokeRect(x0, y, x1 - x0, rowH);

        let cx = x0;
        // Columna nombre (latín + árabe)
        {
          const cw = (x1 - x0) * cols[0].w;
          ctx.textAlign = 'center';
          ctx.fillStyle = C.ink;
          ctx.font = '600 36px Inter, sans-serif';
          ctx.fillText(this._prayerName(p.name), cx + cw / 2, y + 52);
          ctx.fillStyle = C.green;
          ctx.font = '700 34px Amiri, "Noto Naskh Arabic", serif';
          ctx.fillText(this._prayerArabic(p.name), cx + cw / 2, y + 98);
          cx += cw;
        }
        // Adhan
        {
          const cw = (x1 - x0) * cols[1].w;
          ctx.fillStyle = C.ink;
          ctx.font = '700 44px Inter, sans-serif';
          ctx.fillText(this._fmt(p.time), cx + cw / 2, y + rowH / 2 + 15);
          cx += cw;
        }
        // Iqamah
        {
          const cw = (x1 - x0) * cols[2].w;
          if (p.iqamah) {
            ctx.fillStyle = C.gold;
            ctx.font = '700 40px Inter, sans-serif';
            ctx.fillText(this._fmt(p.iqamah), cx + cw / 2, y + rowH / 2 + 14);
          } else {
            ctx.fillStyle = C.muted;
            ctx.font = '400 32px Inter, sans-serif';
            ctx.fillText('—', cx + cw / 2, y + rowH / 2 + 11);
          }
        }
        y += rowH;
      });

      // Nota de Jumuah si hoy es viernes
      if (new Date().getDay() === 5) {
        y += 34;
        ctx.fillStyle = C.friday;
        ctx.fillRect(x0, y, x1 - x0, 84);
        ctx.strokeStyle = C.gold;
        ctx.lineWidth = 2;
        ctx.strokeRect(x0, y, x1 - x0, 84);
        ctx.fillStyle = C.navy;
        ctx.textAlign = 'center';
        ctx.font = '700 30px Amiri, "Noto Naskh Arabic", Inter, sans-serif';
        const j = (typeof t === 'function' && t('jumuahNoticeTime')) || '2:10 PM — La Habana';
        ctx.fillText(`🕌 ${this._L('friday')} — ${j}`, W / 2, y + 53);
      }

      this._drawFooter(ctx);

      const d = new Date();
      const fname = `quba-prayers-${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}.pdf`;
      this._save(canvas, fname);
      if (typeof showToast === 'function') showToast('📄 PDF ✓');
    } catch (e) {
      console.warn('PDF daily error:', e);
      if (typeof showToast === 'function') showToast((typeof t === 'function' && t('errorLoading')) || 'Error');
    } finally {
      this._busy(btn, false);
    }
  },

  // ============ PDF DEL MES ============
  async downloadMonth(btn) {
    this._busy(btn, true);
    try {
      await this._ensureJsPdf();
      if (document.fonts && document.fonts.ready) await document.fonts.ready;
      const monthly = (typeof PrayerPage !== 'undefined') && PrayerPage._monthly;
      if (!monthly || !monthly.data || !monthly.data.length) throw new Error('no monthly data');
      const { data, month, year } = monthly;

      const { canvas, ctx } = this._newCanvas();
      const C = this.COLORS, W = this.PAGE_W;
      const monthName = new Date(year, month - 1).toLocaleString(
        this._lang() === 'ar' ? 'ar-EG' : this._lang(), { month: 'long' }
      );
      let y = await this._drawHeader(ctx, `${this._L('monthTitle')} — ${monthName} ${year}`);

      const x0 = 50, x1 = W - 50;
      const headH = 84;
      // Altura de fila calculada para que todo quepa en UNA página A4
      const footerSpace = 130;
      const avail = this.PAGE_H - y - footerSpace - 90; // 90 = leyenda
      const rowH = Math.min(46, Math.floor(avail / data.length));

      const names = ['Fajr', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'];
      // Columnas: día (doble línea) + 5 oraciones
      const dayW = 250;
      const cw = (x1 - x0 - dayW) / names.length;

      // Cabecera
      ctx.fillStyle = C.navy;
      ctx.fillRect(x0, y, x1 - x0, headH);
      ctx.textAlign = 'center';
      ctx.fillStyle = '#ffffff';
      ctx.font = '700 30px Inter, Amiri, "Noto Naskh Arabic", sans-serif';
      ctx.fillText(this._L('day'), x0 + dayW / 2, y + headH / 2 + 10);
      names.forEach((n, i) => {
        ctx.fillText(this._prayerName(n), x0 + dayW + cw * i + cw / 2, y + 34);
        ctx.font = '700 26px Amiri, "Noto Naskh Arabic", serif';
        ctx.fillStyle = C.gold;
        ctx.fillText(this._prayerArabic(n), x0 + dayW + cw * i + cw / 2, y + 66);
        ctx.fillStyle = '#ffffff';
        ctx.font = '700 30px Inter, Amiri, "Noto Naskh Arabic", sans-serif';
      });
      y += headH;

      const today = new Date();
      const isCurrentMonth = today.getMonth() + 1 === month && today.getFullYear() === year;

      data.forEach((day, i) => {
        const g = day.date?.gregorian;
        const h = day.date?.hijri;
        const dayNum = parseInt(g?.day, 10);
        const isToday = isCurrentMonth && dayNum === today.getDate();
        const iso = g?.date ? g.date.split('-').reverse().join('-') : '';
        const isFriday = iso ? (new Date(iso + 'T00:00:00').getDay() === 5) : false;

        ctx.fillStyle = isToday ? C.today : (isFriday ? C.friday : (i % 2 ? C.rowAlt : '#ffffff'));
        ctx.fillRect(x0, y, x1 - x0, rowH);
        ctx.strokeStyle = C.line;
        ctx.lineWidth = 1;
        ctx.strokeRect(x0, y, x1 - x0, rowH);
        if (isToday) {
          ctx.fillStyle = C.gold;
          ctx.fillRect(x0, y, 7, rowH);
        }

        // Columna día: gregoriano + hijri
        ctx.textAlign = 'center';
        ctx.fillStyle = isFriday ? '#8E6E1E' : C.ink;
        ctx.font = '700 27px Inter, sans-serif';
        const hijriTxt = `${h?.day ?? ''} ${(h?.month?.ar || h?.month?.en || '')}`;
        const gregTxt = `${dayNum}`;
        if (rowH >= 40) {
          ctx.fillText(`${gregTxt}  ·  ${hijriTxt}`, x0 + dayW / 2, y + rowH / 2 + 9);
        } else {
          ctx.fillText(gregTxt, x0 + dayW / 2, y + rowH / 2 + 9);
        }

        // Oraciones (adhan + iqamah pequeña debajo si hay espacio)
        names.forEach((n, j) => {
          const t24 = this._t24(day.timings?.[n]);
          const cx = x0 + dayW + cw * j + cw / 2;
          ctx.fillStyle = C.ink;
          ctx.font = '600 27px Inter, sans-serif';
          if (rowH >= 40) {
            ctx.fillText(t24, cx, y + 20);
            const iq = (typeof getIqamahTime === 'function') ? getIqamahTime(n, t24) : null;
            if (iq) {
              ctx.fillStyle = C.gold;
              ctx.font = '600 20px Inter, sans-serif';
              ctx.fillText(iq, cx, y + rowH - 7);
            }
          } else {
            ctx.fillText(t24, cx, y + rowH / 2 + 9);
          }
        });

        y += rowH;
      });

      // Leyenda
      y += 30;
      ctx.textAlign = 'center';
      ctx.font = '400 25px Inter, Amiri, "Noto Naskh Arabic", sans-serif';
      ctx.fillStyle = C.muted;
      ctx.fillText(`● ${this._L('today')}    ● ${this._L('friday')}`, W / 2, y + 10);
      ctx.fillStyle = C.gold;
      ctx.beginPath(); ctx.arc(W / 2 - ctx.measureText(`● ${this._L('today')}    ● ${this._L('friday')}`).width / 2 - 0, 0, 0, 0, 0); ctx.closePath();

      this._drawFooter(ctx);

      const fname = `quba-prayers-${year}-${String(month).padStart(2, '0')}.pdf`;
      this._save(canvas, fname);
      if (typeof showToast === 'function') showToast('📄 PDF ✓');
    } catch (e) {
      console.warn('PDF month error:', e);
      if (typeof showToast === 'function') showToast((typeof t === 'function' && t('errorLoading')) || 'Error');
    } finally {
      this._busy(btn, false);
    }
  },
};

if (typeof window !== 'undefined') window.PrayerPdf = PrayerPdf;
